/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { ArticleLocalizationsInnerCover } from './ArticleLocalizationsInnerCover';
import {
    ArticleLocalizationsInnerCoverFromJSON,
    ArticleLocalizationsInnerCoverFromJSONTyped,
    ArticleLocalizationsInnerCoverToJSON,
    ArticleLocalizationsInnerCoverToJSONTyped,
} from './ArticleLocalizationsInnerCover';

/**
 * 
 * @export
 * @interface ArticleLocalizationsInner
 */
export interface ArticleLocalizationsInner {
    /**
     * 
     * @type {number}
     * @memberof ArticleLocalizationsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleLocalizationsInner
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleLocalizationsInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleLocalizationsInner
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleLocalizationsInner
     */
    slug?: string;
    /**
     * 
     * @type {ArticleLocalizationsInnerCover}
     * @memberof ArticleLocalizationsInner
     */
    cover?: ArticleLocalizationsInnerCover;
    /**
     * 
     * @type {string}
     * @memberof ArticleLocalizationsInner
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof ArticleLocalizationsInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ArticleLocalizationsInner
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ArticleLocalizationsInner
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ArticleLocalizationsInner
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ArticleLocalizationsInner
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof ArticleLocalizationsInner
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof ArticleLocalizationsInner
     */
    localizations?: Array<ArticleCoverRelatedInner>;
}

/**
 * Check if a given object implements the ArticleLocalizationsInner interface.
 */
export function instanceOfArticleLocalizationsInner(value: object): value is ArticleLocalizationsInner {
    return true;
}

export function ArticleLocalizationsInnerFromJSON(json: any): ArticleLocalizationsInner {
    return ArticleLocalizationsInnerFromJSONTyped(json, false);
}

export function ArticleLocalizationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleLocalizationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'cover': json['cover'] == null ? undefined : ArticleLocalizationsInnerCoverFromJSON(json['cover']),
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
    };
}

export function ArticleLocalizationsInnerToJSON(json: any): ArticleLocalizationsInner {
    return ArticleLocalizationsInnerToJSONTyped(json, false);
}

export function ArticleLocalizationsInnerToJSONTyped(value?: ArticleLocalizationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'title': value['title'],
        'description': value['description'],
        'slug': value['slug'],
        'cover': ArticleLocalizationsInnerCoverToJSON(value['cover']),
        'content': value['content'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
    };
}

