/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { ArticleCoverFolderFilesInner } from './ArticleCoverFolderFilesInner';
import {
    ArticleCoverFolderFilesInnerFromJSON,
    ArticleCoverFolderFilesInnerFromJSONTyped,
    ArticleCoverFolderFilesInnerToJSON,
    ArticleCoverFolderFilesInnerToJSONTyped,
} from './ArticleCoverFolderFilesInner';

/**
 * 
 * @export
 * @interface ArticleCoverFolder
 */
export interface ArticleCoverFolder {
    /**
     * 
     * @type {number}
     * @memberof ArticleCoverFolder
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolder
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolder
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticleCoverFolder
     */
    pathId?: number;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ArticleCoverFolder
     */
    parent?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof ArticleCoverFolder
     */
    children?: Array<ArticleCoverRelatedInner>;
    /**
     * 
     * @type {Array<ArticleCoverFolderFilesInner>}
     * @memberof ArticleCoverFolder
     */
    files?: Array<ArticleCoverFolderFilesInner>;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolder
     */
    path?: string;
    /**
     * 
     * @type {Date}
     * @memberof ArticleCoverFolder
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ArticleCoverFolder
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ArticleCoverFolder
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ArticleCoverFolder
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ArticleCoverFolder
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolder
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof ArticleCoverFolder
     */
    localizations?: Array<ArticleCoverRelatedInner>;
}

/**
 * Check if a given object implements the ArticleCoverFolder interface.
 */
export function instanceOfArticleCoverFolder(value: object): value is ArticleCoverFolder {
    return true;
}

export function ArticleCoverFolderFromJSON(json: any): ArticleCoverFolder {
    return ArticleCoverFolderFromJSONTyped(json, false);
}

export function ArticleCoverFolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleCoverFolder {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'name': json['name'] == null ? undefined : json['name'],
        'pathId': json['pathId'] == null ? undefined : json['pathId'],
        'parent': json['parent'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['parent']),
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(ArticleCoverFolderFilesInnerFromJSON)),
        'path': json['path'] == null ? undefined : json['path'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
    };
}

export function ArticleCoverFolderToJSON(json: any): ArticleCoverFolder {
    return ArticleCoverFolderToJSONTyped(json, false);
}

export function ArticleCoverFolderToJSONTyped(value?: ArticleCoverFolder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'name': value['name'],
        'pathId': value['pathId'],
        'parent': ArticleCoverRelatedInnerToJSON(value['parent']),
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(ArticleCoverFolderFilesInnerToJSON)),
        'path': value['path'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
    };
}

