/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ArticleRequestDataCover
 * 
 * @export
 */
export type ArticleRequestDataCover = number | string;

export function ArticleRequestDataCoverFromJSON(json: any): ArticleRequestDataCover {
    return ArticleRequestDataCoverFromJSONTyped(json, false);
}

export function ArticleRequestDataCoverFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleRequestDataCover {
    if (json == null) {
        return json;
    }
    if (instanceOfnumber(json)) {
        return numberFromJSONTyped(json, true);
    }
    if (instanceOfstring(json)) {
        return stringFromJSONTyped(json, true);
    }

    return {} as any;
}

export function ArticleRequestDataCoverToJSON(json: any): any {
    return ArticleRequestDataCoverToJSONTyped(json, false);
}

export function ArticleRequestDataCoverToJSONTyped(value?: ArticleRequestDataCover | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfnumber(value)) {
        return numberToJSON(value as number);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

