/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleRequestDataCover } from './ArticleRequestDataCover';
import {
    ArticleRequestDataCoverFromJSON,
    ArticleRequestDataCoverFromJSONTyped,
    ArticleRequestDataCoverToJSON,
    ArticleRequestDataCoverToJSONTyped,
} from './ArticleRequestDataCover';

/**
 * 
 * @export
 * @interface ArticleRequestData
 */
export interface ArticleRequestData {
    /**
     * 
     * @type {string}
     * @memberof ArticleRequestData
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleRequestData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleRequestData
     */
    slug?: string;
    /**
     * 
     * @type {ArticleRequestDataCover}
     * @memberof ArticleRequestData
     */
    cover?: ArticleRequestDataCover;
    /**
     * 
     * @type {string}
     * @memberof ArticleRequestData
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleRequestData
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof ArticleRequestData
     */
    localizations?: Array<ArticleRequestDataCover>;
}

/**
 * Check if a given object implements the ArticleRequestData interface.
 */
export function instanceOfArticleRequestData(value: object): value is ArticleRequestData {
    return true;
}

export function ArticleRequestDataFromJSON(json: any): ArticleRequestData {
    return ArticleRequestDataFromJSONTyped(json, false);
}

export function ArticleRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'cover': json['cover'] == null ? undefined : ArticleRequestDataCoverFromJSON(json['cover']),
        'content': json['content'] == null ? undefined : json['content'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
    };
}

export function ArticleRequestDataToJSON(json: any): ArticleRequestData {
    return ArticleRequestDataToJSONTyped(json, false);
}

export function ArticleRequestDataToJSONTyped(value?: ArticleRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'slug': value['slug'],
        'cover': ArticleRequestDataCoverToJSON(value['cover']),
        'content': value['content'],
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
    };
}

