/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { ArticleLocalizationsInner } from './ArticleLocalizationsInner';
import {
    ArticleLocalizationsInnerFromJSON,
    ArticleLocalizationsInnerFromJSONTyped,
    ArticleLocalizationsInnerToJSON,
    ArticleLocalizationsInnerToJSONTyped,
} from './ArticleLocalizationsInner';
import type { ArticleCover } from './ArticleCover';
import {
    ArticleCoverFromJSON,
    ArticleCoverFromJSONTyped,
    ArticleCoverToJSON,
    ArticleCoverToJSONTyped,
} from './ArticleCover';

/**
 * 
 * @export
 * @interface Article
 */
export interface Article {
    /**
     * 
     * @type {number}
     * @memberof Article
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    slug?: string;
    /**
     * 
     * @type {ArticleCover}
     * @memberof Article
     */
    cover?: ArticleCover;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof Article
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Article
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Article
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof Article
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof Article
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleLocalizationsInner>}
     * @memberof Article
     */
    localizations?: Array<ArticleLocalizationsInner>;
}

/**
 * Check if a given object implements the Article interface.
 */
export function instanceOfArticle(value: object): value is Article {
    return true;
}

export function ArticleFromJSON(json: any): Article {
    return ArticleFromJSONTyped(json, false);
}

export function ArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Article {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'cover': json['cover'] == null ? undefined : ArticleCoverFromJSON(json['cover']),
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleLocalizationsInnerFromJSON)),
    };
}

export function ArticleToJSON(json: any): Article {
    return ArticleToJSONTyped(json, false);
}

export function ArticleToJSONTyped(value?: Article | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'title': value['title'],
        'description': value['description'],
        'slug': value['slug'],
        'cover': ArticleCoverToJSON(value['cover']),
        'content': value['content'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleLocalizationsInnerToJSON)),
    };
}

