/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { ArticleCoverFolderFilesInnerCreatedByRolesInner } from './ArticleCoverFolderFilesInnerCreatedByRolesInner';
import {
    ArticleCoverFolderFilesInnerCreatedByRolesInnerFromJSON,
    ArticleCoverFolderFilesInnerCreatedByRolesInnerFromJSONTyped,
    ArticleCoverFolderFilesInnerCreatedByRolesInnerToJSON,
    ArticleCoverFolderFilesInnerCreatedByRolesInnerToJSONTyped,
} from './ArticleCoverFolderFilesInnerCreatedByRolesInner';

/**
 * 
 * @export
 * @interface ArticleCoverFolderFilesInnerCreatedBy
 */
export interface ArticleCoverFolderFilesInnerCreatedBy {
    /**
     * 
     * @type {number}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    firstname?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    lastname?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    resetPasswordToken?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    registrationToken?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    isActive?: boolean;
    /**
     * 
     * @type {Array<ArticleCoverFolderFilesInnerCreatedByRolesInner>}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    roles?: Array<ArticleCoverFolderFilesInnerCreatedByRolesInner>;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    blocked?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    preferedLanguage?: string;
    /**
     * 
     * @type {Date}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof ArticleCoverFolderFilesInnerCreatedBy
     */
    localizations?: Array<ArticleCoverRelatedInner>;
}

/**
 * Check if a given object implements the ArticleCoverFolderFilesInnerCreatedBy interface.
 */
export function instanceOfArticleCoverFolderFilesInnerCreatedBy(value: object): value is ArticleCoverFolderFilesInnerCreatedBy {
    return true;
}

export function ArticleCoverFolderFilesInnerCreatedByFromJSON(json: any): ArticleCoverFolderFilesInnerCreatedBy {
    return ArticleCoverFolderFilesInnerCreatedByFromJSONTyped(json, false);
}

export function ArticleCoverFolderFilesInnerCreatedByFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleCoverFolderFilesInnerCreatedBy {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'firstname': json['firstname'] == null ? undefined : json['firstname'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'resetPasswordToken': json['resetPasswordToken'] == null ? undefined : json['resetPasswordToken'],
        'registrationToken': json['registrationToken'] == null ? undefined : json['registrationToken'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(ArticleCoverFolderFilesInnerCreatedByRolesInnerFromJSON)),
        'blocked': json['blocked'] == null ? undefined : json['blocked'],
        'preferedLanguage': json['preferedLanguage'] == null ? undefined : json['preferedLanguage'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
    };
}

export function ArticleCoverFolderFilesInnerCreatedByToJSON(json: any): ArticleCoverFolderFilesInnerCreatedBy {
    return ArticleCoverFolderFilesInnerCreatedByToJSONTyped(json, false);
}

export function ArticleCoverFolderFilesInnerCreatedByToJSONTyped(value?: ArticleCoverFolderFilesInnerCreatedBy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'firstname': value['firstname'],
        'lastname': value['lastname'],
        'username': value['username'],
        'email': value['email'],
        'resetPasswordToken': value['resetPasswordToken'],
        'registrationToken': value['registrationToken'],
        'isActive': value['isActive'],
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(ArticleCoverFolderFilesInnerCreatedByRolesInnerToJSON)),
        'blocked': value['blocked'],
        'preferedLanguage': value['preferedLanguage'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
    };
}

