/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner } from './ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner';
import {
    ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInnerFromJSON,
    ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInnerFromJSONTyped,
    ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInnerToJSON,
    ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInnerToJSONTyped,
} from './ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner';

/**
 * 
 * @export
 * @interface ArticleCoverFolderFilesInnerCreatedByRolesInner
 */
export interface ArticleCoverFolderFilesInnerCreatedByRolesInner {
    /**
     * 
     * @type {number}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    description?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    users?: Array<ArticleCoverRelatedInner>;
    /**
     * 
     * @type {Array<ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner>}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    permissions?: Array<ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner>;
    /**
     * 
     * @type {Date}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInner
     */
    localizations?: Array<ArticleCoverRelatedInner>;
}

/**
 * Check if a given object implements the ArticleCoverFolderFilesInnerCreatedByRolesInner interface.
 */
export function instanceOfArticleCoverFolderFilesInnerCreatedByRolesInner(value: object): value is ArticleCoverFolderFilesInnerCreatedByRolesInner {
    return true;
}

export function ArticleCoverFolderFilesInnerCreatedByRolesInnerFromJSON(json: any): ArticleCoverFolderFilesInnerCreatedByRolesInner {
    return ArticleCoverFolderFilesInnerCreatedByRolesInnerFromJSONTyped(json, false);
}

export function ArticleCoverFolderFilesInnerCreatedByRolesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleCoverFolderFilesInnerCreatedByRolesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'description': json['description'] == null ? undefined : json['description'],
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
        'permissions': json['permissions'] == null ? undefined : ((json['permissions'] as Array<any>).map(ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInnerFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
    };
}

export function ArticleCoverFolderFilesInnerCreatedByRolesInnerToJSON(json: any): ArticleCoverFolderFilesInnerCreatedByRolesInner {
    return ArticleCoverFolderFilesInnerCreatedByRolesInnerToJSONTyped(json, false);
}

export function ArticleCoverFolderFilesInnerCreatedByRolesInnerToJSONTyped(value?: ArticleCoverFolderFilesInnerCreatedByRolesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'name': value['name'],
        'code': value['code'],
        'description': value['description'],
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
        'permissions': value['permissions'] == null ? undefined : ((value['permissions'] as Array<any>).map(ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInnerToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
    };
}

