/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';

/**
 * 
 * @export
 * @interface ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
 */
export interface ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner {
    /**
     * 
     * @type {number}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    action?: string;
    /**
     * 
     * @type {any}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    actionParameters?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    subject?: string;
    /**
     * 
     * @type {any}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    properties?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    conditions?: any | null;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    role?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {Date}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    localizations?: Array<ArticleCoverRelatedInner>;
}

/**
 * Check if a given object implements the ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner interface.
 */
export function instanceOfArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner(value: object): value is ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner {
    return true;
}

export function ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInnerFromJSON(json: any): ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner {
    return ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInnerFromJSONTyped(json, false);
}

export function ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'action': json['action'] == null ? undefined : json['action'],
        'actionParameters': json['actionParameters'] == null ? undefined : json['actionParameters'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'properties': json['properties'] == null ? undefined : json['properties'],
        'conditions': json['conditions'] == null ? undefined : json['conditions'],
        'role': json['role'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['role']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
    };
}

export function ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInnerToJSON(json: any): ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner {
    return ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInnerToJSONTyped(json, false);
}

export function ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInnerToJSONTyped(value?: ArticleCoverFolderFilesInnerCreatedByRolesInnerPermissionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'action': value['action'],
        'actionParameters': value['actionParameters'],
        'subject': value['subject'],
        'properties': value['properties'],
        'conditions': value['conditions'],
        'role': ArticleCoverRelatedInnerToJSON(value['role']),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
    };
}

