/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleListResponseMeta } from './ArticleListResponseMeta';
import {
    ArticleListResponseMetaFromJSON,
    ArticleListResponseMetaFromJSONTyped,
    ArticleListResponseMetaToJSON,
    ArticleListResponseMetaToJSONTyped,
} from './ArticleListResponseMeta';
import type { Global } from './Global';
import {
    GlobalFromJSON,
    GlobalFromJSONTyped,
    GlobalToJSON,
    GlobalToJSONTyped,
} from './Global';

/**
 * 
 * @export
 * @interface GlobalListResponse
 */
export interface GlobalListResponse {
    /**
     * 
     * @type {Array<Global>}
     * @memberof GlobalListResponse
     */
    data?: Array<Global>;
    /**
     * 
     * @type {ArticleListResponseMeta}
     * @memberof GlobalListResponse
     */
    meta?: ArticleListResponseMeta;
}

/**
 * Check if a given object implements the GlobalListResponse interface.
 */
export function instanceOfGlobalListResponse(value: object): value is GlobalListResponse {
    return true;
}

export function GlobalListResponseFromJSON(json: any): GlobalListResponse {
    return GlobalListResponseFromJSONTyped(json, false);
}

export function GlobalListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GlobalFromJSON)),
        'meta': json['meta'] == null ? undefined : ArticleListResponseMetaFromJSON(json['meta']),
    };
}

export function GlobalListResponseToJSON(json: any): GlobalListResponse {
    return GlobalListResponseToJSONTyped(json, false);
}

export function GlobalListResponseToJSONTyped(value?: GlobalListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GlobalToJSON)),
        'meta': ArticleListResponseMetaToJSON(value['meta']),
    };
}

