/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { SharedSeoComponent } from './SharedSeoComponent';
import {
    SharedSeoComponentFromJSON,
    SharedSeoComponentFromJSONTyped,
    SharedSeoComponentToJSON,
    SharedSeoComponentToJSONTyped,
} from './SharedSeoComponent';
import type { GlobalLocalizationsInner } from './GlobalLocalizationsInner';
import {
    GlobalLocalizationsInnerFromJSON,
    GlobalLocalizationsInnerFromJSONTyped,
    GlobalLocalizationsInnerToJSON,
    GlobalLocalizationsInnerToJSONTyped,
} from './GlobalLocalizationsInner';
import type { ArticleCover } from './ArticleCover';
import {
    ArticleCoverFromJSON,
    ArticleCoverFromJSONTyped,
    ArticleCoverToJSON,
    ArticleCoverToJSONTyped,
} from './ArticleCover';

/**
 * 
 * @export
 * @interface Global
 */
export interface Global {
    /**
     * 
     * @type {number}
     * @memberof Global
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Global
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof Global
     */
    siteName: string;
    /**
     * 
     * @type {ArticleCover}
     * @memberof Global
     */
    favicon?: ArticleCover;
    /**
     * 
     * @type {string}
     * @memberof Global
     */
    siteDescription: string;
    /**
     * 
     * @type {SharedSeoComponent}
     * @memberof Global
     */
    defaultSeo?: SharedSeoComponent;
    /**
     * 
     * @type {Date}
     * @memberof Global
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Global
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Global
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof Global
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof Global
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof Global
     */
    locale?: string;
    /**
     * 
     * @type {Array<GlobalLocalizationsInner>}
     * @memberof Global
     */
    localizations?: Array<GlobalLocalizationsInner>;
}

/**
 * Check if a given object implements the Global interface.
 */
export function instanceOfGlobal(value: object): value is Global {
    if (!('siteName' in value) || value['siteName'] === undefined) return false;
    if (!('siteDescription' in value) || value['siteDescription'] === undefined) return false;
    return true;
}

export function GlobalFromJSON(json: any): Global {
    return GlobalFromJSONTyped(json, false);
}

export function GlobalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Global {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'siteName': json['siteName'],
        'favicon': json['favicon'] == null ? undefined : ArticleCoverFromJSON(json['favicon']),
        'siteDescription': json['siteDescription'],
        'defaultSeo': json['defaultSeo'] == null ? undefined : SharedSeoComponentFromJSON(json['defaultSeo']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(GlobalLocalizationsInnerFromJSON)),
    };
}

export function GlobalToJSON(json: any): Global {
    return GlobalToJSONTyped(json, false);
}

export function GlobalToJSONTyped(value?: Global | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'siteName': value['siteName'],
        'favicon': ArticleCoverToJSON(value['favicon']),
        'siteDescription': value['siteDescription'],
        'defaultSeo': SharedSeoComponentToJSON(value['defaultSeo']),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(GlobalLocalizationsInnerToJSON)),
    };
}

