/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Header } from './Header';
import {
    HeaderFromJSON,
    HeaderFromJSONTyped,
    HeaderToJSON,
    HeaderToJSONTyped,
} from './Header';
import type { ArticleListResponseMeta } from './ArticleListResponseMeta';
import {
    ArticleListResponseMetaFromJSON,
    ArticleListResponseMetaFromJSONTyped,
    ArticleListResponseMetaToJSON,
    ArticleListResponseMetaToJSONTyped,
} from './ArticleListResponseMeta';

/**
 * 
 * @export
 * @interface HeaderListResponse
 */
export interface HeaderListResponse {
    /**
     * 
     * @type {Array<Header>}
     * @memberof HeaderListResponse
     */
    data?: Array<Header>;
    /**
     * 
     * @type {ArticleListResponseMeta}
     * @memberof HeaderListResponse
     */
    meta?: ArticleListResponseMeta;
}

/**
 * Check if a given object implements the HeaderListResponse interface.
 */
export function instanceOfHeaderListResponse(value: object): value is HeaderListResponse {
    return true;
}

export function HeaderListResponseFromJSON(json: any): HeaderListResponse {
    return HeaderListResponseFromJSONTyped(json, false);
}

export function HeaderListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeaderListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(HeaderFromJSON)),
        'meta': json['meta'] == null ? undefined : ArticleListResponseMetaFromJSON(json['meta']),
    };
}

export function HeaderListResponseToJSON(json: any): HeaderListResponse {
    return HeaderListResponseToJSONTyped(json, false);
}

export function HeaderListResponseToJSONTyped(value?: HeaderListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(HeaderToJSON)),
        'meta': ArticleListResponseMetaToJSON(value['meta']),
    };
}

