/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { FitureFeatureComponent } from './FitureFeatureComponent';
import {
    FitureFeatureComponentFromJSON,
    FitureFeatureComponentFromJSONTyped,
    FitureFeatureComponentToJSON,
    FitureFeatureComponentToJSONTyped,
} from './FitureFeatureComponent';

/**
 * 
 * @export
 * @interface HeaderLocalizationsInner
 */
export interface HeaderLocalizationsInner {
    /**
     * 
     * @type {number}
     * @memberof HeaderLocalizationsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof HeaderLocalizationsInner
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof HeaderLocalizationsInner
     */
    tytul?: string;
    /**
     * 
     * @type {string}
     * @memberof HeaderLocalizationsInner
     */
    motto?: string;
    /**
     * 
     * @type {Array<FitureFeatureComponent>}
     * @memberof HeaderLocalizationsInner
     */
    fiture?: Array<FitureFeatureComponent>;
    /**
     * 
     * @type {Date}
     * @memberof HeaderLocalizationsInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof HeaderLocalizationsInner
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof HeaderLocalizationsInner
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof HeaderLocalizationsInner
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof HeaderLocalizationsInner
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof HeaderLocalizationsInner
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof HeaderLocalizationsInner
     */
    localizations?: Array<ArticleCoverRelatedInner>;
}

/**
 * Check if a given object implements the HeaderLocalizationsInner interface.
 */
export function instanceOfHeaderLocalizationsInner(value: object): value is HeaderLocalizationsInner {
    return true;
}

export function HeaderLocalizationsInnerFromJSON(json: any): HeaderLocalizationsInner {
    return HeaderLocalizationsInnerFromJSONTyped(json, false);
}

export function HeaderLocalizationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeaderLocalizationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'tytul': json['Tytul'] == null ? undefined : json['Tytul'],
        'motto': json['Motto'] == null ? undefined : json['Motto'],
        'fiture': json['fiture'] == null ? undefined : ((json['fiture'] as Array<any>).map(FitureFeatureComponentFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
    };
}

export function HeaderLocalizationsInnerToJSON(json: any): HeaderLocalizationsInner {
    return HeaderLocalizationsInnerToJSONTyped(json, false);
}

export function HeaderLocalizationsInnerToJSONTyped(value?: HeaderLocalizationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'Tytul': value['tytul'],
        'Motto': value['motto'],
        'fiture': value['fiture'] == null ? undefined : ((value['fiture'] as Array<any>).map(FitureFeatureComponentToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
    };
}

