/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Header } from './Header';
import {
    HeaderFromJSON,
    HeaderFromJSONTyped,
    HeaderToJSON,
    HeaderToJSONTyped,
} from './Header';

/**
 * 
 * @export
 * @interface HeaderResponse
 */
export interface HeaderResponse {
    /**
     * 
     * @type {Header}
     * @memberof HeaderResponse
     */
    data?: Header;
    /**
     * 
     * @type {object}
     * @memberof HeaderResponse
     */
    meta?: object;
}

/**
 * Check if a given object implements the HeaderResponse interface.
 */
export function instanceOfHeaderResponse(value: object): value is HeaderResponse {
    return true;
}

export function HeaderResponseFromJSON(json: any): HeaderResponse {
    return HeaderResponseFromJSONTyped(json, false);
}

export function HeaderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeaderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : HeaderFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function HeaderResponseToJSON(json: any): HeaderResponse {
    return HeaderResponseToJSONTyped(json, false);
}

export function HeaderResponseToJSONTyped(value?: HeaderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': HeaderToJSON(value['data']),
        'meta': value['meta'],
    };
}

