/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Karnety } from './Karnety';
import {
    KarnetyFromJSON,
    KarnetyFromJSONTyped,
    KarnetyToJSON,
    KarnetyToJSONTyped,
} from './Karnety';
import type { ArticleListResponseMeta } from './ArticleListResponseMeta';
import {
    ArticleListResponseMetaFromJSON,
    ArticleListResponseMetaFromJSONTyped,
    ArticleListResponseMetaToJSON,
    ArticleListResponseMetaToJSONTyped,
} from './ArticleListResponseMeta';

/**
 * 
 * @export
 * @interface KarnetyListResponse
 */
export interface KarnetyListResponse {
    /**
     * 
     * @type {Array<Karnety>}
     * @memberof KarnetyListResponse
     */
    data?: Array<Karnety>;
    /**
     * 
     * @type {ArticleListResponseMeta}
     * @memberof KarnetyListResponse
     */
    meta?: ArticleListResponseMeta;
}

/**
 * Check if a given object implements the KarnetyListResponse interface.
 */
export function instanceOfKarnetyListResponse(value: object): value is KarnetyListResponse {
    return true;
}

export function KarnetyListResponseFromJSON(json: any): KarnetyListResponse {
    return KarnetyListResponseFromJSONTyped(json, false);
}

export function KarnetyListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KarnetyListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(KarnetyFromJSON)),
        'meta': json['meta'] == null ? undefined : ArticleListResponseMetaFromJSON(json['meta']),
    };
}

export function KarnetyListResponseToJSON(json: any): KarnetyListResponse {
    return KarnetyListResponseToJSONTyped(json, false);
}

export function KarnetyListResponseToJSONTyped(value?: KarnetyListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(KarnetyToJSON)),
        'meta': ArticleListResponseMetaToJSON(value['meta']),
    };
}

