/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KarnetyRequestData } from './KarnetyRequestData';
import {
    KarnetyRequestDataFromJSON,
    KarnetyRequestDataFromJSONTyped,
    KarnetyRequestDataToJSON,
    KarnetyRequestDataToJSONTyped,
} from './KarnetyRequestData';

/**
 * 
 * @export
 * @interface KarnetyRequest
 */
export interface KarnetyRequest {
    /**
     * 
     * @type {KarnetyRequestData}
     * @memberof KarnetyRequest
     */
    data: KarnetyRequestData;
}

/**
 * Check if a given object implements the KarnetyRequest interface.
 */
export function instanceOfKarnetyRequest(value: object): value is KarnetyRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function KarnetyRequestFromJSON(json: any): KarnetyRequest {
    return KarnetyRequestFromJSONTyped(json, false);
}

export function KarnetyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KarnetyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': KarnetyRequestDataFromJSON(json['data']),
    };
}

export function KarnetyRequestToJSON(json: any): KarnetyRequest {
    return KarnetyRequestToJSONTyped(json, false);
}

export function KarnetyRequestToJSONTyped(value?: KarnetyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': KarnetyRequestDataToJSON(value['data']),
    };
}

