/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Karnety } from './Karnety';
import {
    KarnetyFromJSON,
    KarnetyFromJSONTyped,
    KarnetyToJSON,
    KarnetyToJSONTyped,
} from './Karnety';

/**
 * 
 * @export
 * @interface KarnetyResponse
 */
export interface KarnetyResponse {
    /**
     * 
     * @type {Karnety}
     * @memberof KarnetyResponse
     */
    data?: Karnety;
    /**
     * 
     * @type {object}
     * @memberof KarnetyResponse
     */
    meta?: object;
}

/**
 * Check if a given object implements the KarnetyResponse interface.
 */
export function instanceOfKarnetyResponse(value: object): value is KarnetyResponse {
    return true;
}

export function KarnetyResponseFromJSON(json: any): KarnetyResponse {
    return KarnetyResponseFromJSONTyped(json, false);
}

export function KarnetyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KarnetyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : KarnetyFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function KarnetyResponseToJSON(json: any): KarnetyResponse {
    return KarnetyResponseToJSONTyped(json, false);
}

export function KarnetyResponseToJSONTyped(value?: KarnetyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': KarnetyToJSON(value['data']),
        'meta': value['meta'],
    };
}

