/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleRequestDataCover } from './ArticleRequestDataCover';
import {
    ArticleRequestDataCoverFromJSON,
    ArticleRequestDataCoverFromJSONTyped,
    ArticleRequestDataCoverToJSON,
    ArticleRequestDataCoverToJSONTyped,
} from './ArticleRequestDataCover';
import type { SharedCennikComponent } from './SharedCennikComponent';
import {
    SharedCennikComponentFromJSON,
    SharedCennikComponentFromJSONTyped,
    SharedCennikComponentToJSON,
    SharedCennikComponentToJSONTyped,
} from './SharedCennikComponent';

/**
 * 
 * @export
 * @interface KarnetyRequestData
 */
export interface KarnetyRequestData {
    /**
     * 
     * @type {string}
     * @memberof KarnetyRequestData
     */
    nazwa?: string;
    /**
     * 
     * @type {SharedCennikComponent}
     * @memberof KarnetyRequestData
     */
    cennik?: SharedCennikComponent;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof KarnetyRequestData
     */
    dostepneStrefy?: Array<ArticleRequestDataCover>;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof KarnetyRequestData
     */
    dostepneZajeciaGrupowe?: Array<ArticleRequestDataCover>;
    /**
     * 
     * @type {string}
     * @memberof KarnetyRequestData
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof KarnetyRequestData
     */
    localizations?: Array<ArticleRequestDataCover>;
}

/**
 * Check if a given object implements the KarnetyRequestData interface.
 */
export function instanceOfKarnetyRequestData(value: object): value is KarnetyRequestData {
    return true;
}

export function KarnetyRequestDataFromJSON(json: any): KarnetyRequestData {
    return KarnetyRequestDataFromJSONTyped(json, false);
}

export function KarnetyRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): KarnetyRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'nazwa': json['nazwa'] == null ? undefined : json['nazwa'],
        'cennik': json['cennik'] == null ? undefined : SharedCennikComponentFromJSON(json['cennik']),
        'dostepneStrefy': json['dostepneStrefy'] == null ? undefined : ((json['dostepneStrefy'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
        'dostepneZajeciaGrupowe': json['dostepneZajeciaGrupowe'] == null ? undefined : ((json['dostepneZajeciaGrupowe'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
    };
}

export function KarnetyRequestDataToJSON(json: any): KarnetyRequestData {
    return KarnetyRequestDataToJSONTyped(json, false);
}

export function KarnetyRequestDataToJSONTyped(value?: KarnetyRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nazwa': value['nazwa'],
        'cennik': SharedCennikComponentToJSON(value['cennik']),
        'dostepneStrefy': value['dostepneStrefy'] == null ? undefined : ((value['dostepneStrefy'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
        'dostepneZajeciaGrupowe': value['dostepneZajeciaGrupowe'] == null ? undefined : ((value['dostepneZajeciaGrupowe'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
    };
}

