/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Kontakt } from './Kontakt';
import {
    KontaktFromJSON,
    KontaktFromJSONTyped,
    KontaktToJSON,
    KontaktToJSONTyped,
} from './Kontakt';

/**
 * 
 * @export
 * @interface KontaktResponse
 */
export interface KontaktResponse {
    /**
     * 
     * @type {Kontakt}
     * @memberof KontaktResponse
     */
    data?: Kontakt;
    /**
     * 
     * @type {object}
     * @memberof KontaktResponse
     */
    meta?: object;
}

/**
 * Check if a given object implements the KontaktResponse interface.
 */
export function instanceOfKontaktResponse(value: object): value is KontaktResponse {
    return true;
}

export function KontaktResponseFromJSON(json: any): KontaktResponse {
    return KontaktResponseFromJSONTyped(json, false);
}

export function KontaktResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KontaktResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : KontaktFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function KontaktResponseToJSON(json: any): KontaktResponse {
    return KontaktResponseToJSONTyped(json, false);
}

export function KontaktResponseToJSONTyped(value?: KontaktResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': KontaktToJSON(value['data']),
        'meta': value['meta'],
    };
}

