/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { SharedOpcjeKontaktoweComponent } from './SharedOpcjeKontaktoweComponent';
import {
    SharedOpcjeKontaktoweComponentFromJSON,
    SharedOpcjeKontaktoweComponentFromJSONTyped,
    SharedOpcjeKontaktoweComponentToJSON,
    SharedOpcjeKontaktoweComponentToJSONTyped,
} from './SharedOpcjeKontaktoweComponent';

/**
 * 
 * @export
 * @interface KontaktLocalizationsInner
 */
export interface KontaktLocalizationsInner {
    /**
     * 
     * @type {number}
     * @memberof KontaktLocalizationsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof KontaktLocalizationsInner
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof KontaktLocalizationsInner
     */
    tytul?: string;
    /**
     * 
     * @type {Array<SharedOpcjeKontaktoweComponent>}
     * @memberof KontaktLocalizationsInner
     */
    opcjeKontaktowe?: Array<SharedOpcjeKontaktoweComponent>;
    /**
     * 
     * @type {Date}
     * @memberof KontaktLocalizationsInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof KontaktLocalizationsInner
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof KontaktLocalizationsInner
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof KontaktLocalizationsInner
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof KontaktLocalizationsInner
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof KontaktLocalizationsInner
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof KontaktLocalizationsInner
     */
    localizations?: Array<ArticleCoverRelatedInner>;
}

/**
 * Check if a given object implements the KontaktLocalizationsInner interface.
 */
export function instanceOfKontaktLocalizationsInner(value: object): value is KontaktLocalizationsInner {
    return true;
}

export function KontaktLocalizationsInnerFromJSON(json: any): KontaktLocalizationsInner {
    return KontaktLocalizationsInnerFromJSONTyped(json, false);
}

export function KontaktLocalizationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): KontaktLocalizationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'tytul': json['tytul'] == null ? undefined : json['tytul'],
        'opcjeKontaktowe': json['opcjeKontaktowe'] == null ? undefined : ((json['opcjeKontaktowe'] as Array<any>).map(SharedOpcjeKontaktoweComponentFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
    };
}

export function KontaktLocalizationsInnerToJSON(json: any): KontaktLocalizationsInner {
    return KontaktLocalizationsInnerToJSONTyped(json, false);
}

export function KontaktLocalizationsInnerToJSONTyped(value?: KontaktLocalizationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'tytul': value['tytul'],
        'opcjeKontaktowe': value['opcjeKontaktowe'] == null ? undefined : ((value['opcjeKontaktowe'] as Array<any>).map(SharedOpcjeKontaktoweComponentToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
    };
}

