/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KontaktRequestData } from './KontaktRequestData';
import {
    KontaktRequestDataFromJSON,
    KontaktRequestDataFromJSONTyped,
    KontaktRequestDataToJSON,
    KontaktRequestDataToJSONTyped,
} from './KontaktRequestData';

/**
 * 
 * @export
 * @interface KontaktRequest
 */
export interface KontaktRequest {
    /**
     * 
     * @type {KontaktRequestData}
     * @memberof KontaktRequest
     */
    data: KontaktRequestData;
}

/**
 * Check if a given object implements the KontaktRequest interface.
 */
export function instanceOfKontaktRequest(value: object): value is KontaktRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function KontaktRequestFromJSON(json: any): KontaktRequest {
    return KontaktRequestFromJSONTyped(json, false);
}

export function KontaktRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KontaktRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': KontaktRequestDataFromJSON(json['data']),
    };
}

export function KontaktRequestToJSON(json: any): KontaktRequest {
    return KontaktRequestToJSONTyped(json, false);
}

export function KontaktRequestToJSONTyped(value?: KontaktRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': KontaktRequestDataToJSON(value['data']),
    };
}

