/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Kontakt } from './Kontakt';
import {
    KontaktFromJSON,
    KontaktFromJSONTyped,
    KontaktToJSON,
    KontaktToJSONTyped,
} from './Kontakt';
import type { ArticleListResponseMeta } from './ArticleListResponseMeta';
import {
    ArticleListResponseMetaFromJSON,
    ArticleListResponseMetaFromJSONTyped,
    ArticleListResponseMetaToJSON,
    ArticleListResponseMetaToJSONTyped,
} from './ArticleListResponseMeta';

/**
 * 
 * @export
 * @interface KontaktListResponse
 */
export interface KontaktListResponse {
    /**
     * 
     * @type {Array<Kontakt>}
     * @memberof KontaktListResponse
     */
    data?: Array<Kontakt>;
    /**
     * 
     * @type {ArticleListResponseMeta}
     * @memberof KontaktListResponse
     */
    meta?: ArticleListResponseMeta;
}

/**
 * Check if a given object implements the KontaktListResponse interface.
 */
export function instanceOfKontaktListResponse(value: object): value is KontaktListResponse {
    return true;
}

export function KontaktListResponseFromJSON(json: any): KontaktListResponse {
    return KontaktListResponseFromJSONTyped(json, false);
}

export function KontaktListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KontaktListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(KontaktFromJSON)),
        'meta': json['meta'] == null ? undefined : ArticleListResponseMetaFromJSON(json['meta']),
    };
}

export function KontaktListResponseToJSON(json: any): KontaktListResponse {
    return KontaktListResponseToJSONTyped(json, false);
}

export function KontaktListResponseToJSONTyped(value?: KontaktListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(KontaktToJSON)),
        'meta': ArticleListResponseMetaToJSON(value['meta']),
    };
}

