/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleRequestDataCover } from './ArticleRequestDataCover';
import {
    ArticleRequestDataCoverFromJSON,
    ArticleRequestDataCoverFromJSONTyped,
    ArticleRequestDataCoverToJSON,
    ArticleRequestDataCoverToJSONTyped,
} from './ArticleRequestDataCover';

/**
 * 
 * @export
 * @interface PromocjaRequestData
 */
export interface PromocjaRequestData {
    /**
     * 
     * @type {string}
     * @memberof PromocjaRequestData
     */
    tytul?: string;
    /**
     * 
     * @type {string}
     * @memberof PromocjaRequestData
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof PromocjaRequestData
     */
    localizations?: Array<ArticleRequestDataCover>;
}

/**
 * Check if a given object implements the PromocjaRequestData interface.
 */
export function instanceOfPromocjaRequestData(value: object): value is PromocjaRequestData {
    return true;
}

export function PromocjaRequestDataFromJSON(json: any): PromocjaRequestData {
    return PromocjaRequestDataFromJSONTyped(json, false);
}

export function PromocjaRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromocjaRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'tytul': json['tytul'] == null ? undefined : json['tytul'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
    };
}

export function PromocjaRequestDataToJSON(json: any): PromocjaRequestData {
    return PromocjaRequestDataToJSONTyped(json, false);
}

export function PromocjaRequestDataToJSONTyped(value?: PromocjaRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tytul': value['tytul'],
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
    };
}

