/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Promocja } from './Promocja';
import {
    PromocjaFromJSON,
    PromocjaFromJSONTyped,
    PromocjaToJSON,
    PromocjaToJSONTyped,
} from './Promocja';
import type { ArticleListResponseMeta } from './ArticleListResponseMeta';
import {
    ArticleListResponseMetaFromJSON,
    ArticleListResponseMetaFromJSONTyped,
    ArticleListResponseMetaToJSON,
    ArticleListResponseMetaToJSONTyped,
} from './ArticleListResponseMeta';

/**
 * 
 * @export
 * @interface PromocjaListResponse
 */
export interface PromocjaListResponse {
    /**
     * 
     * @type {Array<Promocja>}
     * @memberof PromocjaListResponse
     */
    data?: Array<Promocja>;
    /**
     * 
     * @type {ArticleListResponseMeta}
     * @memberof PromocjaListResponse
     */
    meta?: ArticleListResponseMeta;
}

/**
 * Check if a given object implements the PromocjaListResponse interface.
 */
export function instanceOfPromocjaListResponse(value: object): value is PromocjaListResponse {
    return true;
}

export function PromocjaListResponseFromJSON(json: any): PromocjaListResponse {
    return PromocjaListResponseFromJSONTyped(json, false);
}

export function PromocjaListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromocjaListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PromocjaFromJSON)),
        'meta': json['meta'] == null ? undefined : ArticleListResponseMetaFromJSON(json['meta']),
    };
}

export function PromocjaListResponseToJSON(json: any): PromocjaListResponse {
    return PromocjaListResponseToJSONTyped(json, false);
}

export function PromocjaListResponseToJSONTyped(value?: PromocjaListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PromocjaToJSON)),
        'meta': ArticleListResponseMetaToJSON(value['meta']),
    };
}

