/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';

/**
 * 
 * @export
 * @interface PromocjaLocalizationsInner
 */
export interface PromocjaLocalizationsInner {
    /**
     * 
     * @type {number}
     * @memberof PromocjaLocalizationsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PromocjaLocalizationsInner
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof PromocjaLocalizationsInner
     */
    tytul?: string;
    /**
     * 
     * @type {Date}
     * @memberof PromocjaLocalizationsInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PromocjaLocalizationsInner
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PromocjaLocalizationsInner
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof PromocjaLocalizationsInner
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof PromocjaLocalizationsInner
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof PromocjaLocalizationsInner
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof PromocjaLocalizationsInner
     */
    localizations?: Array<ArticleCoverRelatedInner>;
}

/**
 * Check if a given object implements the PromocjaLocalizationsInner interface.
 */
export function instanceOfPromocjaLocalizationsInner(value: object): value is PromocjaLocalizationsInner {
    return true;
}

export function PromocjaLocalizationsInnerFromJSON(json: any): PromocjaLocalizationsInner {
    return PromocjaLocalizationsInnerFromJSONTyped(json, false);
}

export function PromocjaLocalizationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromocjaLocalizationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'tytul': json['tytul'] == null ? undefined : json['tytul'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
    };
}

export function PromocjaLocalizationsInnerToJSON(json: any): PromocjaLocalizationsInner {
    return PromocjaLocalizationsInnerToJSONTyped(json, false);
}

export function PromocjaLocalizationsInnerToJSONTyped(value?: PromocjaLocalizationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'tytul': value['tytul'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
    };
}

