/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PromocjaRequestData } from './PromocjaRequestData';
import {
    PromocjaRequestDataFromJSON,
    PromocjaRequestDataFromJSONTyped,
    PromocjaRequestDataToJSON,
    PromocjaRequestDataToJSONTyped,
} from './PromocjaRequestData';

/**
 * 
 * @export
 * @interface PromocjaRequest
 */
export interface PromocjaRequest {
    /**
     * 
     * @type {PromocjaRequestData}
     * @memberof PromocjaRequest
     */
    data: PromocjaRequestData;
}

/**
 * Check if a given object implements the PromocjaRequest interface.
 */
export function instanceOfPromocjaRequest(value: object): value is PromocjaRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PromocjaRequestFromJSON(json: any): PromocjaRequest {
    return PromocjaRequestFromJSONTyped(json, false);
}

export function PromocjaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromocjaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PromocjaRequestDataFromJSON(json['data']),
    };
}

export function PromocjaRequestToJSON(json: any): PromocjaRequest {
    return PromocjaRequestToJSONTyped(json, false);
}

export function PromocjaRequestToJSONTyped(value?: PromocjaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PromocjaRequestDataToJSON(value['data']),
    };
}

