/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Promocja } from './Promocja';
import {
    PromocjaFromJSON,
    PromocjaFromJSONTyped,
    PromocjaToJSON,
    PromocjaToJSONTyped,
} from './Promocja';

/**
 * 
 * @export
 * @interface PromocjaResponse
 */
export interface PromocjaResponse {
    /**
     * 
     * @type {Promocja}
     * @memberof PromocjaResponse
     */
    data?: Promocja;
    /**
     * 
     * @type {object}
     * @memberof PromocjaResponse
     */
    meta?: object;
}

/**
 * Check if a given object implements the PromocjaResponse interface.
 */
export function instanceOfPromocjaResponse(value: object): value is PromocjaResponse {
    return true;
}

export function PromocjaResponseFromJSON(json: any): PromocjaResponse {
    return PromocjaResponseFromJSONTyped(json, false);
}

export function PromocjaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromocjaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PromocjaFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function PromocjaResponseToJSON(json: any): PromocjaResponse {
    return PromocjaResponseToJSONTyped(json, false);
}

export function PromocjaResponseToJSONTyped(value?: PromocjaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PromocjaToJSON(value['data']),
        'meta': value['meta'],
    };
}

