/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SharedWlasciwosciWspolneComponent } from './SharedWlasciwosciWspolneComponent';
import {
    SharedWlasciwosciWspolneComponentFromJSON,
    SharedWlasciwosciWspolneComponentFromJSONTyped,
    SharedWlasciwosciWspolneComponentToJSON,
    SharedWlasciwosciWspolneComponentToJSONTyped,
} from './SharedWlasciwosciWspolneComponent';
import type { SharedCennikPozycjaComponent } from './SharedCennikPozycjaComponent';
import {
    SharedCennikPozycjaComponentFromJSON,
    SharedCennikPozycjaComponentFromJSONTyped,
    SharedCennikPozycjaComponentToJSON,
    SharedCennikPozycjaComponentToJSONTyped,
} from './SharedCennikPozycjaComponent';

/**
 * 
 * @export
 * @interface SharedCennikComponent
 */
export interface SharedCennikComponent {
    /**
     * 
     * @type {number}
     * @memberof SharedCennikComponent
     */
    id?: number;
    /**
     * 
     * @type {Array<SharedWlasciwosciWspolneComponent>}
     * @memberof SharedCennikComponent
     */
    wlasciwosciWspolne?: Array<SharedWlasciwosciWspolneComponent>;
    /**
     * 
     * @type {Array<SharedCennikPozycjaComponent>}
     * @memberof SharedCennikComponent
     */
    pozycja?: Array<SharedCennikPozycjaComponent>;
}

/**
 * Check if a given object implements the SharedCennikComponent interface.
 */
export function instanceOfSharedCennikComponent(value: object): value is SharedCennikComponent {
    return true;
}

export function SharedCennikComponentFromJSON(json: any): SharedCennikComponent {
    return SharedCennikComponentFromJSONTyped(json, false);
}

export function SharedCennikComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedCennikComponent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'wlasciwosciWspolne': json['wlasciwosciWspolne'] == null ? undefined : ((json['wlasciwosciWspolne'] as Array<any>).map(SharedWlasciwosciWspolneComponentFromJSON)),
        'pozycja': json['pozycja'] == null ? undefined : ((json['pozycja'] as Array<any>).map(SharedCennikPozycjaComponentFromJSON)),
    };
}

export function SharedCennikComponentToJSON(json: any): SharedCennikComponent {
    return SharedCennikComponentToJSONTyped(json, false);
}

export function SharedCennikComponentToJSONTyped(value?: SharedCennikComponent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'wlasciwosciWspolne': value['wlasciwosciWspolne'] == null ? undefined : ((value['wlasciwosciWspolne'] as Array<any>).map(SharedWlasciwosciWspolneComponentToJSON)),
        'pozycja': value['pozycja'] == null ? undefined : ((value['pozycja'] as Array<any>).map(SharedCennikPozycjaComponentToJSON)),
    };
}

