/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SharedWlasciwosciWspolneComponent } from './SharedWlasciwosciWspolneComponent';
import {
    SharedWlasciwosciWspolneComponentFromJSON,
    SharedWlasciwosciWspolneComponentFromJSONTyped,
    SharedWlasciwosciWspolneComponentToJSON,
    SharedWlasciwosciWspolneComponentToJSONTyped,
} from './SharedWlasciwosciWspolneComponent';
import type { ArticleLocalizationsInnerCover } from './ArticleLocalizationsInnerCover';
import {
    ArticleLocalizationsInnerCoverFromJSON,
    ArticleLocalizationsInnerCoverFromJSONTyped,
    ArticleLocalizationsInnerCoverToJSON,
    ArticleLocalizationsInnerCoverToJSONTyped,
} from './ArticleLocalizationsInnerCover';

/**
 * 
 * @export
 * @interface SharedCennikPozycjaComponent
 */
export interface SharedCennikPozycjaComponent {
    /**
     * 
     * @type {number}
     * @memberof SharedCennikPozycjaComponent
     */
    id?: number;
    /**
     * 
     * @type {ArticleLocalizationsInnerCover}
     * @memberof SharedCennikPozycjaComponent
     */
    img?: ArticleLocalizationsInnerCover;
    /**
     * 
     * @type {string}
     * @memberof SharedCennikPozycjaComponent
     */
    nazwa?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedCennikPozycjaComponent
     */
    cena?: string;
    /**
     * 
     * @type {Array<SharedWlasciwosciWspolneComponent>}
     * @memberof SharedCennikPozycjaComponent
     */
    wlasciwosci?: Array<SharedWlasciwosciWspolneComponent>;
}

/**
 * Check if a given object implements the SharedCennikPozycjaComponent interface.
 */
export function instanceOfSharedCennikPozycjaComponent(value: object): value is SharedCennikPozycjaComponent {
    return true;
}

export function SharedCennikPozycjaComponentFromJSON(json: any): SharedCennikPozycjaComponent {
    return SharedCennikPozycjaComponentFromJSONTyped(json, false);
}

export function SharedCennikPozycjaComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedCennikPozycjaComponent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'img': json['img'] == null ? undefined : ArticleLocalizationsInnerCoverFromJSON(json['img']),
        'nazwa': json['nazwa'] == null ? undefined : json['nazwa'],
        'cena': json['cena'] == null ? undefined : json['cena'],
        'wlasciwosci': json['wlasciwosci'] == null ? undefined : ((json['wlasciwosci'] as Array<any>).map(SharedWlasciwosciWspolneComponentFromJSON)),
    };
}

export function SharedCennikPozycjaComponentToJSON(json: any): SharedCennikPozycjaComponent {
    return SharedCennikPozycjaComponentToJSONTyped(json, false);
}

export function SharedCennikPozycjaComponentToJSONTyped(value?: SharedCennikPozycjaComponent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'img': ArticleLocalizationsInnerCoverToJSON(value['img']),
        'nazwa': value['nazwa'],
        'cena': value['cena'],
        'wlasciwosci': value['wlasciwosci'] == null ? undefined : ((value['wlasciwosci'] as Array<any>).map(SharedWlasciwosciWspolneComponentToJSON)),
    };
}

