/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleLocalizationsInnerCover } from './ArticleLocalizationsInnerCover';
import {
    ArticleLocalizationsInnerCoverFromJSON,
    ArticleLocalizationsInnerCoverFromJSONTyped,
    ArticleLocalizationsInnerCoverToJSON,
    ArticleLocalizationsInnerCoverToJSONTyped,
} from './ArticleLocalizationsInnerCover';

/**
 * 
 * @export
 * @interface SharedWlasciwosciWspolneComponent
 */
export interface SharedWlasciwosciWspolneComponent {
    /**
     * 
     * @type {number}
     * @memberof SharedWlasciwosciWspolneComponent
     */
    id?: number;
    /**
     * 
     * @type {ArticleLocalizationsInnerCover}
     * @memberof SharedWlasciwosciWspolneComponent
     */
    icon?: ArticleLocalizationsInnerCover;
    /**
     * 
     * @type {string}
     * @memberof SharedWlasciwosciWspolneComponent
     */
    nazwa?: string;
}

/**
 * Check if a given object implements the SharedWlasciwosciWspolneComponent interface.
 */
export function instanceOfSharedWlasciwosciWspolneComponent(value: object): value is SharedWlasciwosciWspolneComponent {
    return true;
}

export function SharedWlasciwosciWspolneComponentFromJSON(json: any): SharedWlasciwosciWspolneComponent {
    return SharedWlasciwosciWspolneComponentFromJSONTyped(json, false);
}

export function SharedWlasciwosciWspolneComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedWlasciwosciWspolneComponent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'icon': json['icon'] == null ? undefined : ArticleLocalizationsInnerCoverFromJSON(json['icon']),
        'nazwa': json['nazwa'] == null ? undefined : json['nazwa'],
    };
}

export function SharedWlasciwosciWspolneComponentToJSON(json: any): SharedWlasciwosciWspolneComponent {
    return SharedWlasciwosciWspolneComponentToJSONTyped(json, false);
}

export function SharedWlasciwosciWspolneComponentToJSONTyped(value?: SharedWlasciwosciWspolneComponent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'icon': ArticleLocalizationsInnerCoverToJSON(value['icon']),
        'nazwa': value['nazwa'],
    };
}

