/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleLocalizationsInnerCover } from './ArticleLocalizationsInnerCover';
import {
    ArticleLocalizationsInnerCoverFromJSON,
    ArticleLocalizationsInnerCoverFromJSONTyped,
    ArticleLocalizationsInnerCoverToJSON,
    ArticleLocalizationsInnerCoverToJSONTyped,
} from './ArticleLocalizationsInnerCover';

/**
 * 
 * @export
 * @interface SharedOpcjeKontaktoweComponent
 */
export interface SharedOpcjeKontaktoweComponent {
    /**
     * 
     * @type {number}
     * @memberof SharedOpcjeKontaktoweComponent
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SharedOpcjeKontaktoweComponent
     */
    nazwa?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedOpcjeKontaktoweComponent
     */
    opis?: string;
    /**
     * 
     * @type {ArticleLocalizationsInnerCover}
     * @memberof SharedOpcjeKontaktoweComponent
     */
    icon?: ArticleLocalizationsInnerCover;
}

/**
 * Check if a given object implements the SharedOpcjeKontaktoweComponent interface.
 */
export function instanceOfSharedOpcjeKontaktoweComponent(value: object): value is SharedOpcjeKontaktoweComponent {
    return true;
}

export function SharedOpcjeKontaktoweComponentFromJSON(json: any): SharedOpcjeKontaktoweComponent {
    return SharedOpcjeKontaktoweComponentFromJSONTyped(json, false);
}

export function SharedOpcjeKontaktoweComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedOpcjeKontaktoweComponent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nazwa': json['nazwa'] == null ? undefined : json['nazwa'],
        'opis': json['opis'] == null ? undefined : json['opis'],
        'icon': json['icon'] == null ? undefined : ArticleLocalizationsInnerCoverFromJSON(json['icon']),
    };
}

export function SharedOpcjeKontaktoweComponentToJSON(json: any): SharedOpcjeKontaktoweComponent {
    return SharedOpcjeKontaktoweComponentToJSONTyped(json, false);
}

export function SharedOpcjeKontaktoweComponentToJSONTyped(value?: SharedOpcjeKontaktoweComponent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nazwa': value['nazwa'],
        'opis': value['opis'],
        'icon': ArticleLocalizationsInnerCoverToJSON(value['icon']),
    };
}

