/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleLocalizationsInnerCover } from './ArticleLocalizationsInnerCover';
import {
    ArticleLocalizationsInnerCoverFromJSON,
    ArticleLocalizationsInnerCoverFromJSONTyped,
    ArticleLocalizationsInnerCoverToJSON,
    ArticleLocalizationsInnerCoverToJSONTyped,
} from './ArticleLocalizationsInnerCover';

/**
 * 
 * @export
 * @interface SharedSeoComponent
 */
export interface SharedSeoComponent {
    /**
     * 
     * @type {number}
     * @memberof SharedSeoComponent
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SharedSeoComponent
     */
    metaTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedSeoComponent
     */
    metaDescription?: string;
    /**
     * 
     * @type {ArticleLocalizationsInnerCover}
     * @memberof SharedSeoComponent
     */
    shareImage?: ArticleLocalizationsInnerCover;
}

/**
 * Check if a given object implements the SharedSeoComponent interface.
 */
export function instanceOfSharedSeoComponent(value: object): value is SharedSeoComponent {
    return true;
}

export function SharedSeoComponentFromJSON(json: any): SharedSeoComponent {
    return SharedSeoComponentFromJSONTyped(json, false);
}

export function SharedSeoComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedSeoComponent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'metaTitle': json['metaTitle'] == null ? undefined : json['metaTitle'],
        'metaDescription': json['metaDescription'] == null ? undefined : json['metaDescription'],
        'shareImage': json['shareImage'] == null ? undefined : ArticleLocalizationsInnerCoverFromJSON(json['shareImage']),
    };
}

export function SharedSeoComponentToJSON(json: any): SharedSeoComponent {
    return SharedSeoComponentToJSONTyped(json, false);
}

export function SharedSeoComponentToJSONTyped(value?: SharedSeoComponent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'metaTitle': value['metaTitle'],
        'metaDescription': value['metaDescription'],
        'shareImage': ArticleLocalizationsInnerCoverToJSON(value['shareImage']),
    };
}

