/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Strefa } from './Strefa';
import {
    StrefaFromJSON,
    StrefaFromJSONTyped,
    StrefaToJSON,
    StrefaToJSONTyped,
} from './Strefa';
import type { ArticleListResponseMeta } from './ArticleListResponseMeta';
import {
    ArticleListResponseMetaFromJSON,
    ArticleListResponseMetaFromJSONTyped,
    ArticleListResponseMetaToJSON,
    ArticleListResponseMetaToJSONTyped,
} from './ArticleListResponseMeta';

/**
 * 
 * @export
 * @interface StrefaListResponse
 */
export interface StrefaListResponse {
    /**
     * 
     * @type {Array<Strefa>}
     * @memberof StrefaListResponse
     */
    data?: Array<Strefa>;
    /**
     * 
     * @type {ArticleListResponseMeta}
     * @memberof StrefaListResponse
     */
    meta?: ArticleListResponseMeta;
}

/**
 * Check if a given object implements the StrefaListResponse interface.
 */
export function instanceOfStrefaListResponse(value: object): value is StrefaListResponse {
    return true;
}

export function StrefaListResponseFromJSON(json: any): StrefaListResponse {
    return StrefaListResponseFromJSONTyped(json, false);
}

export function StrefaListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrefaListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(StrefaFromJSON)),
        'meta': json['meta'] == null ? undefined : ArticleListResponseMetaFromJSON(json['meta']),
    };
}

export function StrefaListResponseToJSON(json: any): StrefaListResponse {
    return StrefaListResponseToJSONTyped(json, false);
}

export function StrefaListResponseToJSONTyped(value?: StrefaListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(StrefaToJSON)),
        'meta': ArticleListResponseMetaToJSON(value['meta']),
    };
}

