/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Strefa } from './Strefa';
import {
    StrefaFromJSON,
    StrefaFromJSONTyped,
    StrefaToJSON,
    StrefaToJSONTyped,
} from './Strefa';

/**
 * 
 * @export
 * @interface StrefaResponse
 */
export interface StrefaResponse {
    /**
     * 
     * @type {Strefa}
     * @memberof StrefaResponse
     */
    data?: Strefa;
    /**
     * 
     * @type {object}
     * @memberof StrefaResponse
     */
    meta?: object;
}

/**
 * Check if a given object implements the StrefaResponse interface.
 */
export function instanceOfStrefaResponse(value: object): value is StrefaResponse {
    return true;
}

export function StrefaResponseFromJSON(json: any): StrefaResponse {
    return StrefaResponseFromJSONTyped(json, false);
}

export function StrefaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrefaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : StrefaFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function StrefaResponseToJSON(json: any): StrefaResponse {
    return StrefaResponseToJSONTyped(json, false);
}

export function StrefaResponseToJSONTyped(value?: StrefaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': StrefaToJSON(value['data']),
        'meta': value['meta'],
    };
}

