/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleRequestDataCover } from './ArticleRequestDataCover';
import {
    ArticleRequestDataCoverFromJSON,
    ArticleRequestDataCoverFromJSONTyped,
    ArticleRequestDataCoverToJSON,
    ArticleRequestDataCoverToJSONTyped,
} from './ArticleRequestDataCover';
import type { SharedVideoTumbComponent } from './SharedVideoTumbComponent';
import {
    SharedVideoTumbComponentFromJSON,
    SharedVideoTumbComponentFromJSONTyped,
    SharedVideoTumbComponentToJSON,
    SharedVideoTumbComponentToJSONTyped,
} from './SharedVideoTumbComponent';

/**
 * 
 * @export
 * @interface StrefaRequestData
 */
export interface StrefaRequestData {
    /**
     * 
     * @type {string}
     * @memberof StrefaRequestData
     */
    nazwa?: string;
    /**
     * 
     * @type {string}
     * @memberof StrefaRequestData
     */
    opis?: string;
    /**
     * 
     * @type {ArticleRequestDataCover}
     * @memberof StrefaRequestData
     */
    video?: ArticleRequestDataCover;
    /**
     * 
     * @type {SharedVideoTumbComponent}
     * @memberof StrefaRequestData
     */
    media?: SharedVideoTumbComponent;
    /**
     * 
     * @type {string}
     * @memberof StrefaRequestData
     */
    kalendarzURL?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof StrefaRequestData
     */
    karnets?: Array<ArticleRequestDataCover>;
    /**
     * 
     * @type {string}
     * @memberof StrefaRequestData
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof StrefaRequestData
     */
    localizations?: Array<ArticleRequestDataCover>;
}

/**
 * Check if a given object implements the StrefaRequestData interface.
 */
export function instanceOfStrefaRequestData(value: object): value is StrefaRequestData {
    return true;
}

export function StrefaRequestDataFromJSON(json: any): StrefaRequestData {
    return StrefaRequestDataFromJSONTyped(json, false);
}

export function StrefaRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrefaRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'nazwa': json['nazwa'] == null ? undefined : json['nazwa'],
        'opis': json['opis'] == null ? undefined : json['opis'],
        'video': json['video'] == null ? undefined : ArticleRequestDataCoverFromJSON(json['video']),
        'media': json['media'] == null ? undefined : SharedVideoTumbComponentFromJSON(json['media']),
        'kalendarzURL': json['kalendarzURL'] == null ? undefined : json['kalendarzURL'],
        'karnets': json['karnets'] == null ? undefined : ((json['karnets'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
    };
}

export function StrefaRequestDataToJSON(json: any): StrefaRequestData {
    return StrefaRequestDataToJSONTyped(json, false);
}

export function StrefaRequestDataToJSONTyped(value?: StrefaRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nazwa': value['nazwa'],
        'opis': value['opis'],
        'video': ArticleRequestDataCoverToJSON(value['video']),
        'media': SharedVideoTumbComponentToJSON(value['media']),
        'kalendarzURL': value['kalendarzURL'],
        'karnets': value['karnets'] == null ? undefined : ((value['karnets'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
    };
}

