/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { SharedVideoTumbComponent } from './SharedVideoTumbComponent';
import {
    SharedVideoTumbComponentFromJSON,
    SharedVideoTumbComponentFromJSONTyped,
    SharedVideoTumbComponentToJSON,
    SharedVideoTumbComponentToJSONTyped,
} from './SharedVideoTumbComponent';
import type { ArticleLocalizationsInnerCover } from './ArticleLocalizationsInnerCover';
import {
    ArticleLocalizationsInnerCoverFromJSON,
    ArticleLocalizationsInnerCoverFromJSONTyped,
    ArticleLocalizationsInnerCoverToJSON,
    ArticleLocalizationsInnerCoverToJSONTyped,
} from './ArticleLocalizationsInnerCover';

/**
 * 
 * @export
 * @interface StrefaKarnetsInnerDostepneStrefyInner
 */
export interface StrefaKarnetsInnerDostepneStrefyInner {
    /**
     * 
     * @type {number}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    nazwa?: string;
    /**
     * 
     * @type {string}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    opis?: string;
    /**
     * 
     * @type {ArticleLocalizationsInnerCover}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    video?: ArticleLocalizationsInnerCover;
    /**
     * 
     * @type {SharedVideoTumbComponent}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    media?: SharedVideoTumbComponent;
    /**
     * 
     * @type {string}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    kalendarzURL?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    karnets?: Array<ArticleCoverRelatedInner>;
    /**
     * 
     * @type {Date}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof StrefaKarnetsInnerDostepneStrefyInner
     */
    localizations?: Array<ArticleCoverRelatedInner>;
}

/**
 * Check if a given object implements the StrefaKarnetsInnerDostepneStrefyInner interface.
 */
export function instanceOfStrefaKarnetsInnerDostepneStrefyInner(value: object): value is StrefaKarnetsInnerDostepneStrefyInner {
    return true;
}

export function StrefaKarnetsInnerDostepneStrefyInnerFromJSON(json: any): StrefaKarnetsInnerDostepneStrefyInner {
    return StrefaKarnetsInnerDostepneStrefyInnerFromJSONTyped(json, false);
}

export function StrefaKarnetsInnerDostepneStrefyInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrefaKarnetsInnerDostepneStrefyInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'nazwa': json['nazwa'] == null ? undefined : json['nazwa'],
        'opis': json['opis'] == null ? undefined : json['opis'],
        'video': json['video'] == null ? undefined : ArticleLocalizationsInnerCoverFromJSON(json['video']),
        'media': json['media'] == null ? undefined : SharedVideoTumbComponentFromJSON(json['media']),
        'kalendarzURL': json['kalendarzURL'] == null ? undefined : json['kalendarzURL'],
        'karnets': json['karnets'] == null ? undefined : ((json['karnets'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
    };
}

export function StrefaKarnetsInnerDostepneStrefyInnerToJSON(json: any): StrefaKarnetsInnerDostepneStrefyInner {
    return StrefaKarnetsInnerDostepneStrefyInnerToJSONTyped(json, false);
}

export function StrefaKarnetsInnerDostepneStrefyInnerToJSONTyped(value?: StrefaKarnetsInnerDostepneStrefyInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'nazwa': value['nazwa'],
        'opis': value['opis'],
        'video': ArticleLocalizationsInnerCoverToJSON(value['video']),
        'media': SharedVideoTumbComponentToJSON(value['media']),
        'kalendarzURL': value['kalendarzURL'],
        'karnets': value['karnets'] == null ? undefined : ((value['karnets'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
    };
}

