/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleRequestDataCover } from './ArticleRequestDataCover';
import {
    ArticleRequestDataCoverFromJSON,
    ArticleRequestDataCoverFromJSONTyped,
    ArticleRequestDataCoverToJSON,
    ArticleRequestDataCoverToJSONTyped,
} from './ArticleRequestDataCover';

/**
 * 
 * @export
 * @interface TrenerRequestData
 */
export interface TrenerRequestData {
    /**
     * 
     * @type {string}
     * @memberof TrenerRequestData
     */
    imie?: string;
    /**
     * 
     * @type {string}
     * @memberof TrenerRequestData
     */
    opis?: string;
    /**
     * 
     * @type {ArticleRequestDataCover}
     * @memberof TrenerRequestData
     */
    img?: ArticleRequestDataCover;
    /**
     * 
     * @type {string}
     * @memberof TrenerRequestData
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof TrenerRequestData
     */
    localizations?: Array<ArticleRequestDataCover>;
}

/**
 * Check if a given object implements the TrenerRequestData interface.
 */
export function instanceOfTrenerRequestData(value: object): value is TrenerRequestData {
    return true;
}

export function TrenerRequestDataFromJSON(json: any): TrenerRequestData {
    return TrenerRequestDataFromJSONTyped(json, false);
}

export function TrenerRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrenerRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'imie': json['imie'] == null ? undefined : json['imie'],
        'opis': json['opis'] == null ? undefined : json['opis'],
        'img': json['img'] == null ? undefined : ArticleRequestDataCoverFromJSON(json['img']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
    };
}

export function TrenerRequestDataToJSON(json: any): TrenerRequestData {
    return TrenerRequestDataToJSONTyped(json, false);
}

export function TrenerRequestDataToJSONTyped(value?: TrenerRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imie': value['imie'],
        'opis': value['opis'],
        'img': ArticleRequestDataCoverToJSON(value['img']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
    };
}

