/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Trener } from './Trener';
import {
    TrenerFromJSON,
    TrenerFromJSONTyped,
    TrenerToJSON,
    TrenerToJSONTyped,
} from './Trener';
import type { ArticleListResponseMeta } from './ArticleListResponseMeta';
import {
    ArticleListResponseMetaFromJSON,
    ArticleListResponseMetaFromJSONTyped,
    ArticleListResponseMetaToJSON,
    ArticleListResponseMetaToJSONTyped,
} from './ArticleListResponseMeta';

/**
 * 
 * @export
 * @interface TrenerListResponse
 */
export interface TrenerListResponse {
    /**
     * 
     * @type {Array<Trener>}
     * @memberof TrenerListResponse
     */
    data?: Array<Trener>;
    /**
     * 
     * @type {ArticleListResponseMeta}
     * @memberof TrenerListResponse
     */
    meta?: ArticleListResponseMeta;
}

/**
 * Check if a given object implements the TrenerListResponse interface.
 */
export function instanceOfTrenerListResponse(value: object): value is TrenerListResponse {
    return true;
}

export function TrenerListResponseFromJSON(json: any): TrenerListResponse {
    return TrenerListResponseFromJSONTyped(json, false);
}

export function TrenerListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrenerListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TrenerFromJSON)),
        'meta': json['meta'] == null ? undefined : ArticleListResponseMetaFromJSON(json['meta']),
    };
}

export function TrenerListResponseToJSON(json: any): TrenerListResponse {
    return TrenerListResponseToJSONTyped(json, false);
}

export function TrenerListResponseToJSONTyped(value?: TrenerListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TrenerToJSON)),
        'meta': ArticleListResponseMetaToJSON(value['meta']),
    };
}

