/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrenerRequestData } from './TrenerRequestData';
import {
    TrenerRequestDataFromJSON,
    TrenerRequestDataFromJSONTyped,
    TrenerRequestDataToJSON,
    TrenerRequestDataToJSONTyped,
} from './TrenerRequestData';

/**
 * 
 * @export
 * @interface TrenerRequest
 */
export interface TrenerRequest {
    /**
     * 
     * @type {TrenerRequestData}
     * @memberof TrenerRequest
     */
    data: TrenerRequestData;
}

/**
 * Check if a given object implements the TrenerRequest interface.
 */
export function instanceOfTrenerRequest(value: object): value is TrenerRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TrenerRequestFromJSON(json: any): TrenerRequest {
    return TrenerRequestFromJSONTyped(json, false);
}

export function TrenerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrenerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TrenerRequestDataFromJSON(json['data']),
    };
}

export function TrenerRequestToJSON(json: any): TrenerRequest {
    return TrenerRequestToJSONTyped(json, false);
}

export function TrenerRequestToJSONTyped(value?: TrenerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TrenerRequestDataToJSON(value['data']),
    };
}

