/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';

/**
 * 
 * @export
 * @interface UslugaSilowniaLocalizationsInner
 */
export interface UslugaSilowniaLocalizationsInner {
    /**
     * 
     * @type {number}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    tytul?: string;
    /**
     * 
     * @type {string}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    opis?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    wszystkieZajeciaGrupowe?: Array<ArticleCoverRelatedInner>;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    wszystkieStrefy?: Array<ArticleCoverRelatedInner>;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    karnety?: Array<ArticleCoverRelatedInner>;
    /**
     * 
     * @type {Date}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof UslugaSilowniaLocalizationsInner
     */
    localizations?: Array<ArticleCoverRelatedInner>;
}

/**
 * Check if a given object implements the UslugaSilowniaLocalizationsInner interface.
 */
export function instanceOfUslugaSilowniaLocalizationsInner(value: object): value is UslugaSilowniaLocalizationsInner {
    return true;
}

export function UslugaSilowniaLocalizationsInnerFromJSON(json: any): UslugaSilowniaLocalizationsInner {
    return UslugaSilowniaLocalizationsInnerFromJSONTyped(json, false);
}

export function UslugaSilowniaLocalizationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UslugaSilowniaLocalizationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'tytul': json['tytul'] == null ? undefined : json['tytul'],
        'opis': json['opis'] == null ? undefined : json['opis'],
        'wszystkieZajeciaGrupowe': json['wszystkieZajeciaGrupowe'] == null ? undefined : ((json['wszystkieZajeciaGrupowe'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
        'wszystkieStrefy': json['wszystkieStrefy'] == null ? undefined : ((json['wszystkieStrefy'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
        'karnety': json['karnety'] == null ? undefined : ((json['karnety'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
    };
}

export function UslugaSilowniaLocalizationsInnerToJSON(json: any): UslugaSilowniaLocalizationsInner {
    return UslugaSilowniaLocalizationsInnerToJSONTyped(json, false);
}

export function UslugaSilowniaLocalizationsInnerToJSONTyped(value?: UslugaSilowniaLocalizationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'tytul': value['tytul'],
        'opis': value['opis'],
        'wszystkieZajeciaGrupowe': value['wszystkieZajeciaGrupowe'] == null ? undefined : ((value['wszystkieZajeciaGrupowe'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
        'wszystkieStrefy': value['wszystkieStrefy'] == null ? undefined : ((value['wszystkieStrefy'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
        'karnety': value['karnety'] == null ? undefined : ((value['karnety'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
    };
}

