/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UslugiUslugaStandardowaComponent } from './UslugiUslugaStandardowaComponent';
import {
    UslugiUslugaStandardowaComponentFromJSON,
    UslugiUslugaStandardowaComponentFromJSONTyped,
    UslugiUslugaStandardowaComponentToJSON,
    UslugiUslugaStandardowaComponentToJSONTyped,
} from './UslugiUslugaStandardowaComponent';
import type { UslugiSilowniaComponent } from './UslugiSilowniaComponent';
import {
    UslugiSilowniaComponentFromJSON,
    UslugiSilowniaComponentFromJSONTyped,
    UslugiSilowniaComponentToJSON,
    UslugiSilowniaComponentToJSONTyped,
} from './UslugiSilowniaComponent';
import type { ArticleRequestDataCover } from './ArticleRequestDataCover';
import {
    ArticleRequestDataCoverFromJSON,
    ArticleRequestDataCoverFromJSONTyped,
    ArticleRequestDataCoverToJSON,
    ArticleRequestDataCoverToJSONTyped,
} from './ArticleRequestDataCover';

/**
 * 
 * @export
 * @interface UslugiRequestData
 */
export interface UslugiRequestData {
    /**
     * 
     * @type {string}
     * @memberof UslugiRequestData
     */
    nazwa?: string;
    /**
     * 
     * @type {ArticleRequestDataCover}
     * @memberof UslugiRequestData
     */
    tlo?: ArticleRequestDataCover;
    /**
     * 
     * @type {UslugiSilowniaComponent}
     * @memberof UslugiRequestData
     */
    silownia?: UslugiSilowniaComponent;
    /**
     * 
     * @type {Array<UslugiUslugaStandardowaComponent>}
     * @memberof UslugiRequestData
     */
    uslugiStandardowe?: Array<UslugiUslugaStandardowaComponent>;
    /**
     * 
     * @type {string}
     * @memberof UslugiRequestData
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof UslugiRequestData
     */
    localizations?: Array<ArticleRequestDataCover>;
}

/**
 * Check if a given object implements the UslugiRequestData interface.
 */
export function instanceOfUslugiRequestData(value: object): value is UslugiRequestData {
    return true;
}

export function UslugiRequestDataFromJSON(json: any): UslugiRequestData {
    return UslugiRequestDataFromJSONTyped(json, false);
}

export function UslugiRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UslugiRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'nazwa': json['nazwa'] == null ? undefined : json['nazwa'],
        'tlo': json['tlo'] == null ? undefined : ArticleRequestDataCoverFromJSON(json['tlo']),
        'silownia': json['silownia'] == null ? undefined : UslugiSilowniaComponentFromJSON(json['silownia']),
        'uslugiStandardowe': json['uslugiStandardowe'] == null ? undefined : ((json['uslugiStandardowe'] as Array<any>).map(UslugiUslugaStandardowaComponentFromJSON)),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
    };
}

export function UslugiRequestDataToJSON(json: any): UslugiRequestData {
    return UslugiRequestDataToJSONTyped(json, false);
}

export function UslugiRequestDataToJSONTyped(value?: UslugiRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nazwa': value['nazwa'],
        'tlo': ArticleRequestDataCoverToJSON(value['tlo']),
        'silownia': UslugiSilowniaComponentToJSON(value['silownia']),
        'uslugiStandardowe': value['uslugiStandardowe'] == null ? undefined : ((value['uslugiStandardowe'] as Array<any>).map(UslugiUslugaStandardowaComponentToJSON)),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
    };
}

