/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { UslugiUslugaStandardowaComponent } from './UslugiUslugaStandardowaComponent';
import {
    UslugiUslugaStandardowaComponentFromJSON,
    UslugiUslugaStandardowaComponentFromJSONTyped,
    UslugiUslugaStandardowaComponentToJSON,
    UslugiUslugaStandardowaComponentToJSONTyped,
} from './UslugiUslugaStandardowaComponent';
import type { UslugiSilowniaComponent } from './UslugiSilowniaComponent';
import {
    UslugiSilowniaComponentFromJSON,
    UslugiSilowniaComponentFromJSONTyped,
    UslugiSilowniaComponentToJSON,
    UslugiSilowniaComponentToJSONTyped,
} from './UslugiSilowniaComponent';
import type { UslugiLocalizationsInner } from './UslugiLocalizationsInner';
import {
    UslugiLocalizationsInnerFromJSON,
    UslugiLocalizationsInnerFromJSONTyped,
    UslugiLocalizationsInnerToJSON,
    UslugiLocalizationsInnerToJSONTyped,
} from './UslugiLocalizationsInner';
import type { ArticleCover } from './ArticleCover';
import {
    ArticleCoverFromJSON,
    ArticleCoverFromJSONTyped,
    ArticleCoverToJSON,
    ArticleCoverToJSONTyped,
} from './ArticleCover';

/**
 * 
 * @export
 * @interface Uslugi
 */
export interface Uslugi {
    /**
     * 
     * @type {number}
     * @memberof Uslugi
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Uslugi
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof Uslugi
     */
    nazwa?: string;
    /**
     * 
     * @type {ArticleCover}
     * @memberof Uslugi
     */
    tlo?: ArticleCover;
    /**
     * 
     * @type {UslugiSilowniaComponent}
     * @memberof Uslugi
     */
    silownia?: UslugiSilowniaComponent;
    /**
     * 
     * @type {Array<UslugiUslugaStandardowaComponent>}
     * @memberof Uslugi
     */
    uslugiStandardowe?: Array<UslugiUslugaStandardowaComponent>;
    /**
     * 
     * @type {Date}
     * @memberof Uslugi
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Uslugi
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Uslugi
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof Uslugi
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof Uslugi
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof Uslugi
     */
    locale?: string;
    /**
     * 
     * @type {Array<UslugiLocalizationsInner>}
     * @memberof Uslugi
     */
    localizations?: Array<UslugiLocalizationsInner>;
}

/**
 * Check if a given object implements the Uslugi interface.
 */
export function instanceOfUslugi(value: object): value is Uslugi {
    return true;
}

export function UslugiFromJSON(json: any): Uslugi {
    return UslugiFromJSONTyped(json, false);
}

export function UslugiFromJSONTyped(json: any, ignoreDiscriminator: boolean): Uslugi {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'nazwa': json['nazwa'] == null ? undefined : json['nazwa'],
        'tlo': json['tlo'] == null ? undefined : ArticleCoverFromJSON(json['tlo']),
        'silownia': json['silownia'] == null ? undefined : UslugiSilowniaComponentFromJSON(json['silownia']),
        'uslugiStandardowe': json['uslugiStandardowe'] == null ? undefined : ((json['uslugiStandardowe'] as Array<any>).map(UslugiUslugaStandardowaComponentFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(UslugiLocalizationsInnerFromJSON)),
    };
}

export function UslugiToJSON(json: any): Uslugi {
    return UslugiToJSONTyped(json, false);
}

export function UslugiToJSONTyped(value?: Uslugi | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'nazwa': value['nazwa'],
        'tlo': ArticleCoverToJSON(value['tlo']),
        'silownia': UslugiSilowniaComponentToJSON(value['silownia']),
        'uslugiStandardowe': value['uslugiStandardowe'] == null ? undefined : ((value['uslugiStandardowe'] as Array<any>).map(UslugiUslugaStandardowaComponentToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(UslugiLocalizationsInnerToJSON)),
    };
}

