/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { StrefaKarnetsInnerDostepneStrefyInner } from './StrefaKarnetsInnerDostepneStrefyInner';
import {
    StrefaKarnetsInnerDostepneStrefyInnerFromJSON,
    StrefaKarnetsInnerDostepneStrefyInnerFromJSONTyped,
    StrefaKarnetsInnerDostepneStrefyInnerToJSON,
    StrefaKarnetsInnerDostepneStrefyInnerToJSONTyped,
} from './StrefaKarnetsInnerDostepneStrefyInner';
import type { SharedCennikComponent } from './SharedCennikComponent';
import {
    SharedCennikComponentFromJSON,
    SharedCennikComponentFromJSONTyped,
    SharedCennikComponentToJSON,
    SharedCennikComponentToJSONTyped,
} from './SharedCennikComponent';

/**
 * 
 * @export
 * @interface UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
 */
export interface UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner {
    /**
     * 
     * @type {number}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    nazwa?: string;
    /**
     * 
     * @type {SharedCennikComponent}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    cennik?: SharedCennikComponent;
    /**
     * 
     * @type {Array<StrefaKarnetsInnerDostepneStrefyInner>}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    dostepneStrefy?: Array<StrefaKarnetsInnerDostepneStrefyInner>;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    dostepneZajeciaGrupowe?: Array<ArticleCoverRelatedInner>;
    /**
     * 
     * @type {Date}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner
     */
    localizations?: Array<ArticleCoverRelatedInner>;
}

/**
 * Check if a given object implements the UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner interface.
 */
export function instanceOfUslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner(value: object): value is UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner {
    return true;
}

export function UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInnerFromJSON(json: any): UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner {
    return UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInnerFromJSONTyped(json, false);
}

export function UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'nazwa': json['nazwa'] == null ? undefined : json['nazwa'],
        'cennik': json['cennik'] == null ? undefined : SharedCennikComponentFromJSON(json['cennik']),
        'dostepneStrefy': json['dostepneStrefy'] == null ? undefined : ((json['dostepneStrefy'] as Array<any>).map(StrefaKarnetsInnerDostepneStrefyInnerFromJSON)),
        'dostepneZajeciaGrupowe': json['dostepneZajeciaGrupowe'] == null ? undefined : ((json['dostepneZajeciaGrupowe'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
    };
}

export function UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInnerToJSON(json: any): UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner {
    return UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInnerToJSONTyped(json, false);
}

export function UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInnerToJSONTyped(value?: UslugaSilowniaWszystkieZajeciaGrupoweInnerKarnetsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'nazwa': value['nazwa'],
        'cennik': SharedCennikComponentToJSON(value['cennik']),
        'dostepneStrefy': value['dostepneStrefy'] == null ? undefined : ((value['dostepneStrefy'] as Array<any>).map(StrefaKarnetsInnerDostepneStrefyInnerToJSON)),
        'dostepneZajeciaGrupowe': value['dostepneZajeciaGrupowe'] == null ? undefined : ((value['dostepneZajeciaGrupowe'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
    };
}

