/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleLocalizationsInnerCover } from './ArticleLocalizationsInnerCover';
import {
    ArticleLocalizationsInnerCoverFromJSON,
    ArticleLocalizationsInnerCoverFromJSONTyped,
    ArticleLocalizationsInnerCoverToJSON,
    ArticleLocalizationsInnerCoverToJSONTyped,
} from './ArticleLocalizationsInnerCover';
import type { SharedCennikComponent } from './SharedCennikComponent';
import {
    SharedCennikComponentFromJSON,
    SharedCennikComponentFromJSONTyped,
    SharedCennikComponentToJSON,
    SharedCennikComponentToJSONTyped,
} from './SharedCennikComponent';

/**
 * 
 * @export
 * @interface UslugiUslugaStandardowaComponent
 */
export interface UslugiUslugaStandardowaComponent {
    /**
     * 
     * @type {number}
     * @memberof UslugiUslugaStandardowaComponent
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UslugiUslugaStandardowaComponent
     */
    nazwa?: string;
    /**
     * 
     * @type {string}
     * @memberof UslugiUslugaStandardowaComponent
     */
    opis?: string;
    /**
     * 
     * @type {ArticleLocalizationsInnerCover}
     * @memberof UslugiUslugaStandardowaComponent
     */
    video?: ArticleLocalizationsInnerCover;
    /**
     * 
     * @type {SharedCennikComponent}
     * @memberof UslugiUslugaStandardowaComponent
     */
    cennik?: SharedCennikComponent;
    /**
     * 
     * @type {string}
     * @memberof UslugiUslugaStandardowaComponent
     */
    kalendarzURL?: string;
}

/**
 * Check if a given object implements the UslugiUslugaStandardowaComponent interface.
 */
export function instanceOfUslugiUslugaStandardowaComponent(value: object): value is UslugiUslugaStandardowaComponent {
    return true;
}

export function UslugiUslugaStandardowaComponentFromJSON(json: any): UslugiUslugaStandardowaComponent {
    return UslugiUslugaStandardowaComponentFromJSONTyped(json, false);
}

export function UslugiUslugaStandardowaComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UslugiUslugaStandardowaComponent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nazwa': json['nazwa'] == null ? undefined : json['nazwa'],
        'opis': json['opis'] == null ? undefined : json['opis'],
        'video': json['video'] == null ? undefined : ArticleLocalizationsInnerCoverFromJSON(json['video']),
        'cennik': json['cennik'] == null ? undefined : SharedCennikComponentFromJSON(json['cennik']),
        'kalendarzURL': json['kalendarzURL'] == null ? undefined : json['kalendarzURL'],
    };
}

export function UslugiUslugaStandardowaComponentToJSON(json: any): UslugiUslugaStandardowaComponent {
    return UslugiUslugaStandardowaComponentToJSONTyped(json, false);
}

export function UslugiUslugaStandardowaComponentToJSONTyped(value?: UslugiUslugaStandardowaComponent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nazwa': value['nazwa'],
        'opis': value['opis'],
        'video': ArticleLocalizationsInnerCoverToJSON(value['video']),
        'cennik': SharedCennikComponentToJSON(value['cennik']),
        'kalendarzURL': value['kalendarzURL'],
    };
}

