/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UslugiSilowniaComponent
 */
export interface UslugiSilowniaComponent {
    /**
     * 
     * @type {number}
     * @memberof UslugiSilowniaComponent
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UslugiSilowniaComponent
     */
    tytul?: string;
    /**
     * 
     * @type {string}
     * @memberof UslugiSilowniaComponent
     */
    opis?: string;
}

/**
 * Check if a given object implements the UslugiSilowniaComponent interface.
 */
export function instanceOfUslugiSilowniaComponent(value: object): value is UslugiSilowniaComponent {
    return true;
}

export function UslugiSilowniaComponentFromJSON(json: any): UslugiSilowniaComponent {
    return UslugiSilowniaComponentFromJSONTyped(json, false);
}

export function UslugiSilowniaComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UslugiSilowniaComponent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'tytul': json['Tytul'] == null ? undefined : json['Tytul'],
        'opis': json['opis'] == null ? undefined : json['opis'],
    };
}

export function UslugiSilowniaComponentToJSON(json: any): UslugiSilowniaComponent {
    return UslugiSilowniaComponentToJSONTyped(json, false);
}

export function UslugiSilowniaComponentToJSONTyped(value?: UslugiSilowniaComponent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'Tytul': value['tytul'],
        'opis': value['opis'],
    };
}

