/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UslugaSilowniaRequestData } from './UslugaSilowniaRequestData';
import {
    UslugaSilowniaRequestDataFromJSON,
    UslugaSilowniaRequestDataFromJSONTyped,
    UslugaSilowniaRequestDataToJSON,
    UslugaSilowniaRequestDataToJSONTyped,
} from './UslugaSilowniaRequestData';

/**
 * 
 * @export
 * @interface UslugaSilowniaRequest
 */
export interface UslugaSilowniaRequest {
    /**
     * 
     * @type {UslugaSilowniaRequestData}
     * @memberof UslugaSilowniaRequest
     */
    data: UslugaSilowniaRequestData;
}

/**
 * Check if a given object implements the UslugaSilowniaRequest interface.
 */
export function instanceOfUslugaSilowniaRequest(value: object): value is UslugaSilowniaRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UslugaSilowniaRequestFromJSON(json: any): UslugaSilowniaRequest {
    return UslugaSilowniaRequestFromJSONTyped(json, false);
}

export function UslugaSilowniaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UslugaSilowniaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': UslugaSilowniaRequestDataFromJSON(json['data']),
    };
}

export function UslugaSilowniaRequestToJSON(json: any): UslugaSilowniaRequest {
    return UslugaSilowniaRequestToJSONTyped(json, false);
}

export function UslugaSilowniaRequestToJSONTyped(value?: UslugaSilowniaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': UslugaSilowniaRequestDataToJSON(value['data']),
    };
}

