/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UslugaSilownia } from './UslugaSilownia';
import {
    UslugaSilowniaFromJSON,
    UslugaSilowniaFromJSONTyped,
    UslugaSilowniaToJSON,
    UslugaSilowniaToJSONTyped,
} from './UslugaSilownia';

/**
 * 
 * @export
 * @interface UslugaSilowniaResponse
 */
export interface UslugaSilowniaResponse {
    /**
     * 
     * @type {UslugaSilownia}
     * @memberof UslugaSilowniaResponse
     */
    data?: UslugaSilownia;
    /**
     * 
     * @type {object}
     * @memberof UslugaSilowniaResponse
     */
    meta?: object;
}

/**
 * Check if a given object implements the UslugaSilowniaResponse interface.
 */
export function instanceOfUslugaSilowniaResponse(value: object): value is UslugaSilowniaResponse {
    return true;
}

export function UslugaSilowniaResponseFromJSON(json: any): UslugaSilowniaResponse {
    return UslugaSilowniaResponseFromJSONTyped(json, false);
}

export function UslugaSilowniaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UslugaSilowniaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : UslugaSilowniaFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function UslugaSilowniaResponseToJSON(json: any): UslugaSilowniaResponse {
    return UslugaSilowniaResponseToJSONTyped(json, false);
}

export function UslugaSilowniaResponseToJSONTyped(value?: UslugaSilowniaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': UslugaSilowniaToJSON(value['data']),
        'meta': value['meta'],
    };
}

