/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UslugaSilownia } from './UslugaSilownia';
import {
    UslugaSilowniaFromJSON,
    UslugaSilowniaFromJSONTyped,
    UslugaSilowniaToJSON,
    UslugaSilowniaToJSONTyped,
} from './UslugaSilownia';
import type { ArticleListResponseMeta } from './ArticleListResponseMeta';
import {
    ArticleListResponseMetaFromJSON,
    ArticleListResponseMetaFromJSONTyped,
    ArticleListResponseMetaToJSON,
    ArticleListResponseMetaToJSONTyped,
} from './ArticleListResponseMeta';

/**
 * 
 * @export
 * @interface UslugaSilowniaListResponse
 */
export interface UslugaSilowniaListResponse {
    /**
     * 
     * @type {Array<UslugaSilownia>}
     * @memberof UslugaSilowniaListResponse
     */
    data?: Array<UslugaSilownia>;
    /**
     * 
     * @type {ArticleListResponseMeta}
     * @memberof UslugaSilowniaListResponse
     */
    meta?: ArticleListResponseMeta;
}

/**
 * Check if a given object implements the UslugaSilowniaListResponse interface.
 */
export function instanceOfUslugaSilowniaListResponse(value: object): value is UslugaSilowniaListResponse {
    return true;
}

export function UslugaSilowniaListResponseFromJSON(json: any): UslugaSilowniaListResponse {
    return UslugaSilowniaListResponseFromJSONTyped(json, false);
}

export function UslugaSilowniaListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UslugaSilowniaListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(UslugaSilowniaFromJSON)),
        'meta': json['meta'] == null ? undefined : ArticleListResponseMetaFromJSON(json['meta']),
    };
}

export function UslugaSilowniaListResponseToJSON(json: any): UslugaSilowniaListResponse {
    return UslugaSilowniaListResponseToJSONTyped(json, false);
}

export function UslugaSilowniaListResponseToJSONTyped(value?: UslugaSilowniaListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(UslugaSilowniaToJSON)),
        'meta': ArticleListResponseMetaToJSON(value['meta']),
    };
}

