/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { ZajeciaIndywidualneTrenerzyInner } from './ZajeciaIndywidualneTrenerzyInner';
import {
    ZajeciaIndywidualneTrenerzyInnerFromJSON,
    ZajeciaIndywidualneTrenerzyInnerFromJSONTyped,
    ZajeciaIndywidualneTrenerzyInnerToJSON,
    ZajeciaIndywidualneTrenerzyInnerToJSONTyped,
} from './ZajeciaIndywidualneTrenerzyInner';
import type { ZajeciaIndywidualneLocalizationsInner } from './ZajeciaIndywidualneLocalizationsInner';
import {
    ZajeciaIndywidualneLocalizationsInnerFromJSON,
    ZajeciaIndywidualneLocalizationsInnerFromJSONTyped,
    ZajeciaIndywidualneLocalizationsInnerToJSON,
    ZajeciaIndywidualneLocalizationsInnerToJSONTyped,
} from './ZajeciaIndywidualneLocalizationsInner';
import type { SharedCennikComponent } from './SharedCennikComponent';
import {
    SharedCennikComponentFromJSON,
    SharedCennikComponentFromJSONTyped,
    SharedCennikComponentToJSON,
    SharedCennikComponentToJSONTyped,
} from './SharedCennikComponent';

/**
 * 
 * @export
 * @interface ZajeciaIndywidualne
 */
export interface ZajeciaIndywidualne {
    /**
     * 
     * @type {number}
     * @memberof ZajeciaIndywidualne
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaIndywidualne
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaIndywidualne
     */
    tytul?: string;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaIndywidualne
     */
    opis?: string;
    /**
     * 
     * @type {Array<ZajeciaIndywidualneTrenerzyInner>}
     * @memberof ZajeciaIndywidualne
     */
    trenerzy?: Array<ZajeciaIndywidualneTrenerzyInner>;
    /**
     * 
     * @type {SharedCennikComponent}
     * @memberof ZajeciaIndywidualne
     */
    cennik?: SharedCennikComponent;
    /**
     * 
     * @type {Date}
     * @memberof ZajeciaIndywidualne
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ZajeciaIndywidualne
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ZajeciaIndywidualne
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ZajeciaIndywidualne
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ZajeciaIndywidualne
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaIndywidualne
     */
    locale?: string;
    /**
     * 
     * @type {Array<ZajeciaIndywidualneLocalizationsInner>}
     * @memberof ZajeciaIndywidualne
     */
    localizations?: Array<ZajeciaIndywidualneLocalizationsInner>;
}

/**
 * Check if a given object implements the ZajeciaIndywidualne interface.
 */
export function instanceOfZajeciaIndywidualne(value: object): value is ZajeciaIndywidualne {
    return true;
}

export function ZajeciaIndywidualneFromJSON(json: any): ZajeciaIndywidualne {
    return ZajeciaIndywidualneFromJSONTyped(json, false);
}

export function ZajeciaIndywidualneFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZajeciaIndywidualne {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'tytul': json['tytul'] == null ? undefined : json['tytul'],
        'opis': json['opis'] == null ? undefined : json['opis'],
        'trenerzy': json['trenerzy'] == null ? undefined : ((json['trenerzy'] as Array<any>).map(ZajeciaIndywidualneTrenerzyInnerFromJSON)),
        'cennik': json['cennik'] == null ? undefined : SharedCennikComponentFromJSON(json['cennik']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ZajeciaIndywidualneLocalizationsInnerFromJSON)),
    };
}

export function ZajeciaIndywidualneToJSON(json: any): ZajeciaIndywidualne {
    return ZajeciaIndywidualneToJSONTyped(json, false);
}

export function ZajeciaIndywidualneToJSONTyped(value?: ZajeciaIndywidualne | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'tytul': value['tytul'],
        'opis': value['opis'],
        'trenerzy': value['trenerzy'] == null ? undefined : ((value['trenerzy'] as Array<any>).map(ZajeciaIndywidualneTrenerzyInnerToJSON)),
        'cennik': SharedCennikComponentToJSON(value['cennik']),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ZajeciaIndywidualneLocalizationsInnerToJSON)),
    };
}

