/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ZajecieGrupoweRequestData } from './ZajecieGrupoweRequestData';
import {
    ZajecieGrupoweRequestDataFromJSON,
    ZajecieGrupoweRequestDataFromJSONTyped,
    ZajecieGrupoweRequestDataToJSON,
    ZajecieGrupoweRequestDataToJSONTyped,
} from './ZajecieGrupoweRequestData';

/**
 * 
 * @export
 * @interface ZajecieGrupoweRequest
 */
export interface ZajecieGrupoweRequest {
    /**
     * 
     * @type {ZajecieGrupoweRequestData}
     * @memberof ZajecieGrupoweRequest
     */
    data: ZajecieGrupoweRequestData;
}

/**
 * Check if a given object implements the ZajecieGrupoweRequest interface.
 */
export function instanceOfZajecieGrupoweRequest(value: object): value is ZajecieGrupoweRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ZajecieGrupoweRequestFromJSON(json: any): ZajecieGrupoweRequest {
    return ZajecieGrupoweRequestFromJSONTyped(json, false);
}

export function ZajecieGrupoweRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZajecieGrupoweRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ZajecieGrupoweRequestDataFromJSON(json['data']),
    };
}

export function ZajecieGrupoweRequestToJSON(json: any): ZajecieGrupoweRequest {
    return ZajecieGrupoweRequestToJSONTyped(json, false);
}

export function ZajecieGrupoweRequestToJSONTyped(value?: ZajecieGrupoweRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ZajecieGrupoweRequestDataToJSON(value['data']),
    };
}

