/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleRequestDataCover } from './ArticleRequestDataCover';
import {
    ArticleRequestDataCoverFromJSON,
    ArticleRequestDataCoverFromJSONTyped,
    ArticleRequestDataCoverToJSON,
    ArticleRequestDataCoverToJSONTyped,
} from './ArticleRequestDataCover';

/**
 * 
 * @export
 * @interface ZajecieGrupoweRequestData
 */
export interface ZajecieGrupoweRequestData {
    /**
     * 
     * @type {string}
     * @memberof ZajecieGrupoweRequestData
     */
    nazwa?: string;
    /**
     * 
     * @type {string}
     * @memberof ZajecieGrupoweRequestData
     */
    opis?: string;
    /**
     * 
     * @type {ArticleRequestDataCover}
     * @memberof ZajecieGrupoweRequestData
     */
    img?: ArticleRequestDataCover;
    /**
     * 
     * @type {ArticleRequestDataCover}
     * @memberof ZajecieGrupoweRequestData
     */
    video?: ArticleRequestDataCover;
    /**
     * 
     * @type {string}
     * @memberof ZajecieGrupoweRequestData
     */
    kalendarzURL?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof ZajecieGrupoweRequestData
     */
    karnets?: Array<ArticleRequestDataCover>;
    /**
     * 
     * @type {string}
     * @memberof ZajecieGrupoweRequestData
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof ZajecieGrupoweRequestData
     */
    localizations?: Array<ArticleRequestDataCover>;
}

/**
 * Check if a given object implements the ZajecieGrupoweRequestData interface.
 */
export function instanceOfZajecieGrupoweRequestData(value: object): value is ZajecieGrupoweRequestData {
    return true;
}

export function ZajecieGrupoweRequestDataFromJSON(json: any): ZajecieGrupoweRequestData {
    return ZajecieGrupoweRequestDataFromJSONTyped(json, false);
}

export function ZajecieGrupoweRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZajecieGrupoweRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'nazwa': json['nazwa'] == null ? undefined : json['nazwa'],
        'opis': json['opis'] == null ? undefined : json['opis'],
        'img': json['img'] == null ? undefined : ArticleRequestDataCoverFromJSON(json['img']),
        'video': json['video'] == null ? undefined : ArticleRequestDataCoverFromJSON(json['video']),
        'kalendarzURL': json['kalendarzURL'] == null ? undefined : json['kalendarzURL'],
        'karnets': json['karnets'] == null ? undefined : ((json['karnets'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
    };
}

export function ZajecieGrupoweRequestDataToJSON(json: any): ZajecieGrupoweRequestData {
    return ZajecieGrupoweRequestDataToJSONTyped(json, false);
}

export function ZajecieGrupoweRequestDataToJSONTyped(value?: ZajecieGrupoweRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nazwa': value['nazwa'],
        'opis': value['opis'],
        'img': ArticleRequestDataCoverToJSON(value['img']),
        'video': ArticleRequestDataCoverToJSON(value['video']),
        'kalendarzURL': value['kalendarzURL'],
        'karnets': value['karnets'] == null ? undefined : ((value['karnets'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
    };
}

