/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ZajeciaGrupowe } from './ZajeciaGrupowe';
import {
    ZajeciaGrupoweFromJSON,
    ZajeciaGrupoweFromJSONTyped,
    ZajeciaGrupoweToJSON,
    ZajeciaGrupoweToJSONTyped,
} from './ZajeciaGrupowe';
import type { ArticleListResponseMeta } from './ArticleListResponseMeta';
import {
    ArticleListResponseMetaFromJSON,
    ArticleListResponseMetaFromJSONTyped,
    ArticleListResponseMetaToJSON,
    ArticleListResponseMetaToJSONTyped,
} from './ArticleListResponseMeta';

/**
 * 
 * @export
 * @interface ZajeciaGrupoweListResponse
 */
export interface ZajeciaGrupoweListResponse {
    /**
     * 
     * @type {Array<ZajeciaGrupowe>}
     * @memberof ZajeciaGrupoweListResponse
     */
    data?: Array<ZajeciaGrupowe>;
    /**
     * 
     * @type {ArticleListResponseMeta}
     * @memberof ZajeciaGrupoweListResponse
     */
    meta?: ArticleListResponseMeta;
}

/**
 * Check if a given object implements the ZajeciaGrupoweListResponse interface.
 */
export function instanceOfZajeciaGrupoweListResponse(value: object): value is ZajeciaGrupoweListResponse {
    return true;
}

export function ZajeciaGrupoweListResponseFromJSON(json: any): ZajeciaGrupoweListResponse {
    return ZajeciaGrupoweListResponseFromJSONTyped(json, false);
}

export function ZajeciaGrupoweListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZajeciaGrupoweListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ZajeciaGrupoweFromJSON)),
        'meta': json['meta'] == null ? undefined : ArticleListResponseMetaFromJSON(json['meta']),
    };
}

export function ZajeciaGrupoweListResponseToJSON(json: any): ZajeciaGrupoweListResponse {
    return ZajeciaGrupoweListResponseToJSONTyped(json, false);
}

export function ZajeciaGrupoweListResponseToJSONTyped(value?: ZajeciaGrupoweListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ZajeciaGrupoweToJSON)),
        'meta': ArticleListResponseMetaToJSON(value['meta']),
    };
}

