/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ZajecieGrupowe } from './ZajecieGrupowe';
import {
    ZajecieGrupoweFromJSON,
    ZajecieGrupoweFromJSONTyped,
    ZajecieGrupoweToJSON,
    ZajecieGrupoweToJSONTyped,
} from './ZajecieGrupowe';

/**
 * 
 * @export
 * @interface ZajecieGrupoweResponse
 */
export interface ZajecieGrupoweResponse {
    /**
     * 
     * @type {ZajecieGrupowe}
     * @memberof ZajecieGrupoweResponse
     */
    data?: ZajecieGrupowe;
    /**
     * 
     * @type {object}
     * @memberof ZajecieGrupoweResponse
     */
    meta?: object;
}

/**
 * Check if a given object implements the ZajecieGrupoweResponse interface.
 */
export function instanceOfZajecieGrupoweResponse(value: object): value is ZajecieGrupoweResponse {
    return true;
}

export function ZajecieGrupoweResponseFromJSON(json: any): ZajecieGrupoweResponse {
    return ZajecieGrupoweResponseFromJSONTyped(json, false);
}

export function ZajecieGrupoweResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZajecieGrupoweResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ZajecieGrupoweFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function ZajecieGrupoweResponseToJSON(json: any): ZajecieGrupoweResponse {
    return ZajecieGrupoweResponseToJSONTyped(json, false);
}

export function ZajecieGrupoweResponseToJSONTyped(value?: ZajecieGrupoweResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ZajecieGrupoweToJSON(value['data']),
        'meta': value['meta'],
    };
}

