/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { UslugaSilowniaWszystkieZajeciaGrupoweInner } from './UslugaSilowniaWszystkieZajeciaGrupoweInner';
import {
    UslugaSilowniaWszystkieZajeciaGrupoweInnerFromJSON,
    UslugaSilowniaWszystkieZajeciaGrupoweInnerFromJSONTyped,
    UslugaSilowniaWszystkieZajeciaGrupoweInnerToJSON,
    UslugaSilowniaWszystkieZajeciaGrupoweInnerToJSONTyped,
} from './UslugaSilowniaWszystkieZajeciaGrupoweInner';
import type { ZajeciaGrupoweLocalizationsInner } from './ZajeciaGrupoweLocalizationsInner';
import {
    ZajeciaGrupoweLocalizationsInnerFromJSON,
    ZajeciaGrupoweLocalizationsInnerFromJSONTyped,
    ZajeciaGrupoweLocalizationsInnerToJSON,
    ZajeciaGrupoweLocalizationsInnerToJSONTyped,
} from './ZajeciaGrupoweLocalizationsInner';

/**
 * 
 * @export
 * @interface ZajeciaGrupowe
 */
export interface ZajeciaGrupowe {
    /**
     * 
     * @type {number}
     * @memberof ZajeciaGrupowe
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaGrupowe
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaGrupowe
     */
    tytul?: string;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaGrupowe
     */
    kalendarzURL?: string;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaGrupowe
     */
    opis?: string;
    /**
     * 
     * @type {Array<UslugaSilowniaWszystkieZajeciaGrupoweInner>}
     * @memberof ZajeciaGrupowe
     */
    zajeciaGrupowe?: Array<UslugaSilowniaWszystkieZajeciaGrupoweInner>;
    /**
     * 
     * @type {Date}
     * @memberof ZajeciaGrupowe
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ZajeciaGrupowe
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ZajeciaGrupowe
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ZajeciaGrupowe
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ZajeciaGrupowe
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaGrupowe
     */
    locale?: string;
    /**
     * 
     * @type {Array<ZajeciaGrupoweLocalizationsInner>}
     * @memberof ZajeciaGrupowe
     */
    localizations?: Array<ZajeciaGrupoweLocalizationsInner>;
}

/**
 * Check if a given object implements the ZajeciaGrupowe interface.
 */
export function instanceOfZajeciaGrupowe(value: object): value is ZajeciaGrupowe {
    return true;
}

export function ZajeciaGrupoweFromJSON(json: any): ZajeciaGrupowe {
    return ZajeciaGrupoweFromJSONTyped(json, false);
}

export function ZajeciaGrupoweFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZajeciaGrupowe {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'tytul': json['tytul'] == null ? undefined : json['tytul'],
        'kalendarzURL': json['kalendarzURL'] == null ? undefined : json['kalendarzURL'],
        'opis': json['opis'] == null ? undefined : json['opis'],
        'zajeciaGrupowe': json['zajeciaGrupowe'] == null ? undefined : ((json['zajeciaGrupowe'] as Array<any>).map(UslugaSilowniaWszystkieZajeciaGrupoweInnerFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ZajeciaGrupoweLocalizationsInnerFromJSON)),
    };
}

export function ZajeciaGrupoweToJSON(json: any): ZajeciaGrupowe {
    return ZajeciaGrupoweToJSONTyped(json, false);
}

export function ZajeciaGrupoweToJSONTyped(value?: ZajeciaGrupowe | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'tytul': value['tytul'],
        'kalendarzURL': value['kalendarzURL'],
        'opis': value['opis'],
        'zajeciaGrupowe': value['zajeciaGrupowe'] == null ? undefined : ((value['zajeciaGrupowe'] as Array<any>).map(UslugaSilowniaWszystkieZajeciaGrupoweInnerToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ZajeciaGrupoweLocalizationsInnerToJSON)),
    };
}

