/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleRequestDataCover } from './ArticleRequestDataCover';
import {
    ArticleRequestDataCoverFromJSON,
    ArticleRequestDataCoverFromJSONTyped,
    ArticleRequestDataCoverToJSON,
    ArticleRequestDataCoverToJSONTyped,
} from './ArticleRequestDataCover';
import type { SharedCennikComponent } from './SharedCennikComponent';
import {
    SharedCennikComponentFromJSON,
    SharedCennikComponentFromJSONTyped,
    SharedCennikComponentToJSON,
    SharedCennikComponentToJSONTyped,
} from './SharedCennikComponent';

/**
 * 
 * @export
 * @interface ZajeciaIndywidualneRequestData
 */
export interface ZajeciaIndywidualneRequestData {
    /**
     * 
     * @type {string}
     * @memberof ZajeciaIndywidualneRequestData
     */
    tytul?: string;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaIndywidualneRequestData
     */
    opis?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof ZajeciaIndywidualneRequestData
     */
    trenerzy?: Array<ArticleRequestDataCover>;
    /**
     * 
     * @type {SharedCennikComponent}
     * @memberof ZajeciaIndywidualneRequestData
     */
    cennik?: SharedCennikComponent;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaIndywidualneRequestData
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCover>}
     * @memberof ZajeciaIndywidualneRequestData
     */
    localizations?: Array<ArticleRequestDataCover>;
}

/**
 * Check if a given object implements the ZajeciaIndywidualneRequestData interface.
 */
export function instanceOfZajeciaIndywidualneRequestData(value: object): value is ZajeciaIndywidualneRequestData {
    return true;
}

export function ZajeciaIndywidualneRequestDataFromJSON(json: any): ZajeciaIndywidualneRequestData {
    return ZajeciaIndywidualneRequestDataFromJSONTyped(json, false);
}

export function ZajeciaIndywidualneRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZajeciaIndywidualneRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'tytul': json['tytul'] == null ? undefined : json['tytul'],
        'opis': json['opis'] == null ? undefined : json['opis'],
        'trenerzy': json['trenerzy'] == null ? undefined : ((json['trenerzy'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
        'cennik': json['cennik'] == null ? undefined : SharedCennikComponentFromJSON(json['cennik']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleRequestDataCoverFromJSON)),
    };
}

export function ZajeciaIndywidualneRequestDataToJSON(json: any): ZajeciaIndywidualneRequestData {
    return ZajeciaIndywidualneRequestDataToJSONTyped(json, false);
}

export function ZajeciaIndywidualneRequestDataToJSONTyped(value?: ZajeciaIndywidualneRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tytul': value['tytul'],
        'opis': value['opis'],
        'trenerzy': value['trenerzy'] == null ? undefined : ((value['trenerzy'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
        'cennik': SharedCennikComponentToJSON(value['cennik']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleRequestDataCoverToJSON)),
    };
}

