/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ZajeciaGrupowe } from './ZajeciaGrupowe';
import {
    ZajeciaGrupoweFromJSON,
    ZajeciaGrupoweFromJSONTyped,
    ZajeciaGrupoweToJSON,
    ZajeciaGrupoweToJSONTyped,
} from './ZajeciaGrupowe';

/**
 * 
 * @export
 * @interface ZajeciaGrupoweResponse
 */
export interface ZajeciaGrupoweResponse {
    /**
     * 
     * @type {ZajeciaGrupowe}
     * @memberof ZajeciaGrupoweResponse
     */
    data?: ZajeciaGrupowe;
    /**
     * 
     * @type {object}
     * @memberof ZajeciaGrupoweResponse
     */
    meta?: object;
}

/**
 * Check if a given object implements the ZajeciaGrupoweResponse interface.
 */
export function instanceOfZajeciaGrupoweResponse(value: object): value is ZajeciaGrupoweResponse {
    return true;
}

export function ZajeciaGrupoweResponseFromJSON(json: any): ZajeciaGrupoweResponse {
    return ZajeciaGrupoweResponseFromJSONTyped(json, false);
}

export function ZajeciaGrupoweResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZajeciaGrupoweResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ZajeciaGrupoweFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function ZajeciaGrupoweResponseToJSON(json: any): ZajeciaGrupoweResponse {
    return ZajeciaGrupoweResponseToJSONTyped(json, false);
}

export function ZajeciaGrupoweResponseToJSONTyped(value?: ZajeciaGrupoweResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ZajeciaGrupoweToJSON(value['data']),
        'meta': value['meta'],
    };
}

