/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ZajeciaIndywidualne } from './ZajeciaIndywidualne';
import {
    ZajeciaIndywidualneFromJSON,
    ZajeciaIndywidualneFromJSONTyped,
    ZajeciaIndywidualneToJSON,
    ZajeciaIndywidualneToJSONTyped,
} from './ZajeciaIndywidualne';

/**
 * 
 * @export
 * @interface ZajeciaIndywidualneResponse
 */
export interface ZajeciaIndywidualneResponse {
    /**
     * 
     * @type {ZajeciaIndywidualne}
     * @memberof ZajeciaIndywidualneResponse
     */
    data?: ZajeciaIndywidualne;
    /**
     * 
     * @type {object}
     * @memberof ZajeciaIndywidualneResponse
     */
    meta?: object;
}

/**
 * Check if a given object implements the ZajeciaIndywidualneResponse interface.
 */
export function instanceOfZajeciaIndywidualneResponse(value: object): value is ZajeciaIndywidualneResponse {
    return true;
}

export function ZajeciaIndywidualneResponseFromJSON(json: any): ZajeciaIndywidualneResponse {
    return ZajeciaIndywidualneResponseFromJSONTyped(json, false);
}

export function ZajeciaIndywidualneResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZajeciaIndywidualneResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ZajeciaIndywidualneFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function ZajeciaIndywidualneResponseToJSON(json: any): ZajeciaIndywidualneResponse {
    return ZajeciaIndywidualneResponseToJSONTyped(json, false);
}

export function ZajeciaIndywidualneResponseToJSONTyped(value?: ZajeciaIndywidualneResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ZajeciaIndywidualneToJSON(value['data']),
        'meta': value['meta'],
    };
}

