/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverRelatedInner } from './ArticleCoverRelatedInner';
import {
    ArticleCoverRelatedInnerFromJSON,
    ArticleCoverRelatedInnerFromJSONTyped,
    ArticleCoverRelatedInnerToJSON,
    ArticleCoverRelatedInnerToJSONTyped,
} from './ArticleCoverRelatedInner';
import type { ArticleCover } from './ArticleCover';
import {
    ArticleCoverFromJSON,
    ArticleCoverFromJSONTyped,
    ArticleCoverToJSON,
    ArticleCoverToJSONTyped,
} from './ArticleCover';

/**
 * 
 * @export
 * @interface ZajeciaIndywidualneTrenerzyInner
 */
export interface ZajeciaIndywidualneTrenerzyInner {
    /**
     * 
     * @type {number}
     * @memberof ZajeciaIndywidualneTrenerzyInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaIndywidualneTrenerzyInner
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaIndywidualneTrenerzyInner
     */
    imie?: string;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaIndywidualneTrenerzyInner
     */
    opis?: string;
    /**
     * 
     * @type {ArticleCover}
     * @memberof ZajeciaIndywidualneTrenerzyInner
     */
    img?: ArticleCover;
    /**
     * 
     * @type {Date}
     * @memberof ZajeciaIndywidualneTrenerzyInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ZajeciaIndywidualneTrenerzyInner
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ZajeciaIndywidualneTrenerzyInner
     */
    publishedAt?: Date;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ZajeciaIndywidualneTrenerzyInner
     */
    createdBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {ArticleCoverRelatedInner}
     * @memberof ZajeciaIndywidualneTrenerzyInner
     */
    updatedBy?: ArticleCoverRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof ZajeciaIndywidualneTrenerzyInner
     */
    locale?: string;
    /**
     * 
     * @type {Array<ArticleCoverRelatedInner>}
     * @memberof ZajeciaIndywidualneTrenerzyInner
     */
    localizations?: Array<ArticleCoverRelatedInner>;
}

/**
 * Check if a given object implements the ZajeciaIndywidualneTrenerzyInner interface.
 */
export function instanceOfZajeciaIndywidualneTrenerzyInner(value: object): value is ZajeciaIndywidualneTrenerzyInner {
    return true;
}

export function ZajeciaIndywidualneTrenerzyInnerFromJSON(json: any): ZajeciaIndywidualneTrenerzyInner {
    return ZajeciaIndywidualneTrenerzyInnerFromJSONTyped(json, false);
}

export function ZajeciaIndywidualneTrenerzyInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZajeciaIndywidualneTrenerzyInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'imie': json['imie'] == null ? undefined : json['imie'],
        'opis': json['opis'] == null ? undefined : json['opis'],
        'img': json['img'] == null ? undefined : ArticleCoverFromJSON(json['img']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['createdBy']),
        'updatedBy': json['updatedBy'] == null ? undefined : ArticleCoverRelatedInnerFromJSON(json['updatedBy']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'localizations': json['localizations'] == null ? undefined : ((json['localizations'] as Array<any>).map(ArticleCoverRelatedInnerFromJSON)),
    };
}

export function ZajeciaIndywidualneTrenerzyInnerToJSON(json: any): ZajeciaIndywidualneTrenerzyInner {
    return ZajeciaIndywidualneTrenerzyInnerToJSONTyped(json, false);
}

export function ZajeciaIndywidualneTrenerzyInnerToJSONTyped(value?: ZajeciaIndywidualneTrenerzyInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'imie': value['imie'],
        'opis': value['opis'],
        'img': ArticleCoverToJSON(value['img']),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'createdBy': ArticleCoverRelatedInnerToJSON(value['createdBy']),
        'updatedBy': ArticleCoverRelatedInnerToJSON(value['updatedBy']),
        'locale': value['locale'],
        'localizations': value['localizations'] == null ? undefined : ((value['localizations'] as Array<any>).map(ArticleCoverRelatedInnerToJSON)),
    };
}

