/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ZajecieGrupowe } from './ZajecieGrupowe';
import {
    ZajecieGrupoweFromJSON,
    ZajecieGrupoweFromJSONTyped,
    ZajecieGrupoweToJSON,
    ZajecieGrupoweToJSONTyped,
} from './ZajecieGrupowe';
import type { ArticleListResponseMeta } from './ArticleListResponseMeta';
import {
    ArticleListResponseMetaFromJSON,
    ArticleListResponseMetaFromJSONTyped,
    ArticleListResponseMetaToJSON,
    ArticleListResponseMetaToJSONTyped,
} from './ArticleListResponseMeta';

/**
 * 
 * @export
 * @interface ZajecieGrupoweListResponse
 */
export interface ZajecieGrupoweListResponse {
    /**
     * 
     * @type {Array<ZajecieGrupowe>}
     * @memberof ZajecieGrupoweListResponse
     */
    data?: Array<ZajecieGrupowe>;
    /**
     * 
     * @type {ArticleListResponseMeta}
     * @memberof ZajecieGrupoweListResponse
     */
    meta?: ArticleListResponseMeta;
}

/**
 * Check if a given object implements the ZajecieGrupoweListResponse interface.
 */
export function instanceOfZajecieGrupoweListResponse(value: object): value is ZajecieGrupoweListResponse {
    return true;
}

export function ZajecieGrupoweListResponseFromJSON(json: any): ZajecieGrupoweListResponse {
    return ZajecieGrupoweListResponseFromJSONTyped(json, false);
}

export function ZajecieGrupoweListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZajecieGrupoweListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ZajecieGrupoweFromJSON)),
        'meta': json['meta'] == null ? undefined : ArticleListResponseMetaFromJSON(json['meta']),
    };
}

export function ZajecieGrupoweListResponseToJSON(json: any): ZajecieGrupoweListResponse {
    return ZajecieGrupoweListResponseToJSONTyped(json, false);
}

export function ZajecieGrupoweListResponseToJSONTyped(value?: ZajecieGrupoweListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ZajecieGrupoweToJSON)),
        'meta': ArticleListResponseMetaToJSON(value['meta']),
    };
}

