/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ZajeciaIndywidualne } from './ZajeciaIndywidualne';
import {
    ZajeciaIndywidualneFromJSON,
    ZajeciaIndywidualneFromJSONTyped,
    ZajeciaIndywidualneToJSON,
    ZajeciaIndywidualneToJSONTyped,
} from './ZajeciaIndywidualne';
import type { ArticleListResponseMeta } from './ArticleListResponseMeta';
import {
    ArticleListResponseMetaFromJSON,
    ArticleListResponseMetaFromJSONTyped,
    ArticleListResponseMetaToJSON,
    ArticleListResponseMetaToJSONTyped,
} from './ArticleListResponseMeta';

/**
 * 
 * @export
 * @interface ZajeciaIndywidualneListResponse
 */
export interface ZajeciaIndywidualneListResponse {
    /**
     * 
     * @type {Array<ZajeciaIndywidualne>}
     * @memberof ZajeciaIndywidualneListResponse
     */
    data?: Array<ZajeciaIndywidualne>;
    /**
     * 
     * @type {ArticleListResponseMeta}
     * @memberof ZajeciaIndywidualneListResponse
     */
    meta?: ArticleListResponseMeta;
}

/**
 * Check if a given object implements the ZajeciaIndywidualneListResponse interface.
 */
export function instanceOfZajeciaIndywidualneListResponse(value: object): value is ZajeciaIndywidualneListResponse {
    return true;
}

export function ZajeciaIndywidualneListResponseFromJSON(json: any): ZajeciaIndywidualneListResponse {
    return ZajeciaIndywidualneListResponseFromJSONTyped(json, false);
}

export function ZajeciaIndywidualneListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZajeciaIndywidualneListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ZajeciaIndywidualneFromJSON)),
        'meta': json['meta'] == null ? undefined : ArticleListResponseMetaFromJSON(json['meta']),
    };
}

export function ZajeciaIndywidualneListResponseToJSON(json: any): ZajeciaIndywidualneListResponse {
    return ZajeciaIndywidualneListResponseToJSONTyped(json, false);
}

export function ZajeciaIndywidualneListResponseToJSONTyped(value?: ZajeciaIndywidualneListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ZajeciaIndywidualneToJSON)),
        'meta': ArticleListResponseMetaToJSON(value['meta']),
    };
}

