/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  StrefaListResponse,
  StrefaRequest,
  StrefaResponse,
} from '../models/index';
import {
    StrefaListResponseFromJSON,
    StrefaListResponseToJSON,
    StrefaRequestFromJSON,
    StrefaRequestToJSON,
    StrefaResponseFromJSON,
    StrefaResponseToJSON,
} from '../models/index';

export interface DeleteStrefasIdRequest {
    id: number;
}

export interface GetStrefasRequest {
    sort?: string;
    paginationWithCount?: boolean;
    paginationPage?: number;
    paginationPageSize?: number;
    paginationStart?: number;
    paginationLimit?: number;
    fields?: string;
    populate?: string;
    filters?: { [key: string]: any; };
    locale?: string;
}

export interface GetStrefasIdRequest {
    id: number;
}

export interface PostStrefasRequest {
    strefaRequest: StrefaRequest;
}

export interface PutStrefasIdRequest {
    id: number;
    strefaRequest: StrefaRequest;
}

/**
 * 
 */
export class StrefaApi extends runtime.BaseAPI {

    /**
     */
    async deleteStrefasIdRaw(requestParameters: DeleteStrefasIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteStrefasId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/strefas/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async deleteStrefasId(requestParameters: DeleteStrefasIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.deleteStrefasIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStrefasRaw(requestParameters: GetStrefasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StrefaListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['paginationWithCount'] != null) {
            queryParameters['pagination[withCount]'] = requestParameters['paginationWithCount'];
        }

        if (requestParameters['paginationPage'] != null) {
            queryParameters['pagination[page]'] = requestParameters['paginationPage'];
        }

        if (requestParameters['paginationPageSize'] != null) {
            queryParameters['pagination[pageSize]'] = requestParameters['paginationPageSize'];
        }

        if (requestParameters['paginationStart'] != null) {
            queryParameters['pagination[start]'] = requestParameters['paginationStart'];
        }

        if (requestParameters['paginationLimit'] != null) {
            queryParameters['pagination[limit]'] = requestParameters['paginationLimit'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['populate'] != null) {
            queryParameters['populate'] = requestParameters['populate'];
        }

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        if (requestParameters['locale'] != null) {
            queryParameters['locale'] = requestParameters['locale'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/strefas`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StrefaListResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStrefas(requestParameters: GetStrefasRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StrefaListResponse> {
        const response = await this.getStrefasRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStrefasIdRaw(requestParameters: GetStrefasIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StrefaResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getStrefasId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/strefas/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StrefaResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStrefasId(requestParameters: GetStrefasIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StrefaResponse> {
        const response = await this.getStrefasIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postStrefasRaw(requestParameters: PostStrefasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StrefaResponse>> {
        if (requestParameters['strefaRequest'] == null) {
            throw new runtime.RequiredError(
                'strefaRequest',
                'Required parameter "strefaRequest" was null or undefined when calling postStrefas().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/strefas`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StrefaRequestToJSON(requestParameters['strefaRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StrefaResponseFromJSON(jsonValue));
    }

    /**
     */
    async postStrefas(requestParameters: PostStrefasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StrefaResponse> {
        const response = await this.postStrefasRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async putStrefasIdRaw(requestParameters: PutStrefasIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StrefaResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putStrefasId().'
            );
        }

        if (requestParameters['strefaRequest'] == null) {
            throw new runtime.RequiredError(
                'strefaRequest',
                'Required parameter "strefaRequest" was null or undefined when calling putStrefasId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/strefas/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StrefaRequestToJSON(requestParameters['strefaRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StrefaResponseFromJSON(jsonValue));
    }

    /**
     */
    async putStrefasId(requestParameters: PutStrefasIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StrefaResponse> {
        const response = await this.putStrefasIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
