/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UslugaSilowniaRequest,
  UslugaSilowniaResponse,
} from '../models/index';
import {
    UslugaSilowniaRequestFromJSON,
    UslugaSilowniaRequestToJSON,
    UslugaSilowniaResponseFromJSON,
    UslugaSilowniaResponseToJSON,
} from '../models/index';

export interface GetUslugaSilowniaRequest {
    sort?: string;
    paginationWithCount?: boolean;
    paginationPage?: number;
    paginationPageSize?: number;
    paginationStart?: number;
    paginationLimit?: number;
    fields?: string;
    populate?: string;
    filters?: { [key: string]: any; };
    locale?: string;
}

export interface PutUslugaSilowniaRequest {
    uslugaSilowniaRequest: UslugaSilowniaRequest;
}

/**
 * 
 */
export class UslugaSilowniaApi extends runtime.BaseAPI {

    /**
     */
    async deleteUslugaSilowniaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/usluga-silownia`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async deleteUslugaSilownia(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.deleteUslugaSilowniaRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getUslugaSilowniaRaw(requestParameters: GetUslugaSilowniaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UslugaSilowniaResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['paginationWithCount'] != null) {
            queryParameters['pagination[withCount]'] = requestParameters['paginationWithCount'];
        }

        if (requestParameters['paginationPage'] != null) {
            queryParameters['pagination[page]'] = requestParameters['paginationPage'];
        }

        if (requestParameters['paginationPageSize'] != null) {
            queryParameters['pagination[pageSize]'] = requestParameters['paginationPageSize'];
        }

        if (requestParameters['paginationStart'] != null) {
            queryParameters['pagination[start]'] = requestParameters['paginationStart'];
        }

        if (requestParameters['paginationLimit'] != null) {
            queryParameters['pagination[limit]'] = requestParameters['paginationLimit'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['populate'] != null) {
            queryParameters['populate'] = requestParameters['populate'];
        }

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        if (requestParameters['locale'] != null) {
            queryParameters['locale'] = requestParameters['locale'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/usluga-silownia`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UslugaSilowniaResponseFromJSON(jsonValue));
    }

    /**
     */
    async getUslugaSilownia(requestParameters: GetUslugaSilowniaRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UslugaSilowniaResponse> {
        const response = await this.getUslugaSilowniaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async putUslugaSilowniaRaw(requestParameters: PutUslugaSilowniaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UslugaSilowniaResponse>> {
        if (requestParameters['uslugaSilowniaRequest'] == null) {
            throw new runtime.RequiredError(
                'uslugaSilowniaRequest',
                'Required parameter "uslugaSilowniaRequest" was null or undefined when calling putUslugaSilownia().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/usluga-silownia`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UslugaSilowniaRequestToJSON(requestParameters['uslugaSilowniaRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UslugaSilowniaResponseFromJSON(jsonValue));
    }

    /**
     */
    async putUslugaSilownia(requestParameters: PutUslugaSilowniaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UslugaSilowniaResponse> {
        const response = await this.putUslugaSilowniaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
