/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ZajecieGrupoweListResponse,
  ZajecieGrupoweRequest,
  ZajecieGrupoweResponse,
} from '../models/index';
import {
    ZajecieGrupoweListResponseFromJSON,
    ZajecieGrupoweListResponseToJSON,
    ZajecieGrupoweRequestFromJSON,
    ZajecieGrupoweRequestToJSON,
    ZajecieGrupoweResponseFromJSON,
    ZajecieGrupoweResponseToJSON,
} from '../models/index';

export interface DeleteZajecieGrupowesIdRequest {
    id: number;
}

export interface GetZajecieGrupowesRequest {
    sort?: string;
    paginationWithCount?: boolean;
    paginationPage?: number;
    paginationPageSize?: number;
    paginationStart?: number;
    paginationLimit?: number;
    fields?: string;
    populate?: string;
    filters?: { [key: string]: any; };
    locale?: string;
}

export interface GetZajecieGrupowesIdRequest {
    id: number;
}

export interface PostZajecieGrupowesRequest {
    zajecieGrupoweRequest: ZajecieGrupoweRequest;
}

export interface PutZajecieGrupowesIdRequest {
    id: number;
    zajecieGrupoweRequest: ZajecieGrupoweRequest;
}

/**
 * 
 */
export class ZajecieGrupoweApi extends runtime.BaseAPI {

    /**
     */
    async deleteZajecieGrupowesIdRaw(requestParameters: DeleteZajecieGrupowesIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteZajecieGrupowesId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zajecie-grupowes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async deleteZajecieGrupowesId(requestParameters: DeleteZajecieGrupowesIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.deleteZajecieGrupowesIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getZajecieGrupowesRaw(requestParameters: GetZajecieGrupowesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ZajecieGrupoweListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['paginationWithCount'] != null) {
            queryParameters['pagination[withCount]'] = requestParameters['paginationWithCount'];
        }

        if (requestParameters['paginationPage'] != null) {
            queryParameters['pagination[page]'] = requestParameters['paginationPage'];
        }

        if (requestParameters['paginationPageSize'] != null) {
            queryParameters['pagination[pageSize]'] = requestParameters['paginationPageSize'];
        }

        if (requestParameters['paginationStart'] != null) {
            queryParameters['pagination[start]'] = requestParameters['paginationStart'];
        }

        if (requestParameters['paginationLimit'] != null) {
            queryParameters['pagination[limit]'] = requestParameters['paginationLimit'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['populate'] != null) {
            queryParameters['populate'] = requestParameters['populate'];
        }

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        if (requestParameters['locale'] != null) {
            queryParameters['locale'] = requestParameters['locale'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zajecie-grupowes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ZajecieGrupoweListResponseFromJSON(jsonValue));
    }

    /**
     */
    async getZajecieGrupowes(requestParameters: GetZajecieGrupowesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ZajecieGrupoweListResponse> {
        const response = await this.getZajecieGrupowesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getZajecieGrupowesIdRaw(requestParameters: GetZajecieGrupowesIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ZajecieGrupoweResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getZajecieGrupowesId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zajecie-grupowes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ZajecieGrupoweResponseFromJSON(jsonValue));
    }

    /**
     */
    async getZajecieGrupowesId(requestParameters: GetZajecieGrupowesIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ZajecieGrupoweResponse> {
        const response = await this.getZajecieGrupowesIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postZajecieGrupowesRaw(requestParameters: PostZajecieGrupowesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ZajecieGrupoweResponse>> {
        if (requestParameters['zajecieGrupoweRequest'] == null) {
            throw new runtime.RequiredError(
                'zajecieGrupoweRequest',
                'Required parameter "zajecieGrupoweRequest" was null or undefined when calling postZajecieGrupowes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zajecie-grupowes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ZajecieGrupoweRequestToJSON(requestParameters['zajecieGrupoweRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ZajecieGrupoweResponseFromJSON(jsonValue));
    }

    /**
     */
    async postZajecieGrupowes(requestParameters: PostZajecieGrupowesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ZajecieGrupoweResponse> {
        const response = await this.postZajecieGrupowesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async putZajecieGrupowesIdRaw(requestParameters: PutZajecieGrupowesIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ZajecieGrupoweResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putZajecieGrupowesId().'
            );
        }

        if (requestParameters['zajecieGrupoweRequest'] == null) {
            throw new runtime.RequiredError(
                'zajecieGrupoweRequest',
                'Required parameter "zajecieGrupoweRequest" was null or undefined when calling putZajecieGrupowesId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zajecie-grupowes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ZajecieGrupoweRequestToJSON(requestParameters['zajecieGrupoweRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ZajecieGrupoweResponseFromJSON(jsonValue));
    }

    /**
     */
    async putZajecieGrupowesId(requestParameters: PutZajecieGrupowesIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ZajecieGrupoweResponse> {
        const response = await this.putZajecieGrupowesIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
